Repository fleetdm/fleet, pull requests merged in 2020-11, with the labels that each got.

#3 Update build documentation
  docs/development/building-the-code.md
  docs/infrastructure/adding-hosts-to-fleet.md
Labels: documentation

#2 Fix handling of --quiet flag in fleetctl query
  cmd/fleetctl/query.go
Labels: bug

#4 Add pretty-printing option for query results
  cmd/fleetctl/query.go
  cmd/fleetctl/query_output.go
  go.mod
  go.sum
Labels: enhancement

#6 Fix regression in list hosts
  server/datastore/datastore_hosts_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/hosts.go
Labels: bug

#1 Updated 500 page copy and added button to reveal error message.
  frontend/interfaces/errors500.js
  frontend/pages/Kolide500/Kolide500.jsx
  frontend/pages/Kolide500/_styles.scss
  frontend/redux/nodes/errors500/actions.js
  frontend/redux/nodes/errors500/reducer.js
  frontend/redux/nodes/errors500/reducer.tests.js
  frontend/redux/reducers.js
Labels: enhancement

#5 Make enroll secret and node key validation case-sensitive
  server/datastore/datastore_app_test.go
  server/datastore/datastore_hosts_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/migrations/tables/20201102112520_ModifyEnrollSecretNodeKeyCollation.go
Labels: bug

#9 Implement fleetctl user create
  CHANGELOG.md
  cmd/fleet/prepare.go
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/user.go
  go.mod
  go.sum
  server/kolide/users.go
  server/service/client_users.go
  server/service/endpoint_setup.go
  server/service/endpoint_users.go
  server/service/handler.go
  server/service/logging_users.go
  server/service/metrics_users.go
  server/service/service_users.go
  server/service/service_users_test.go
  server/service/validation_users.go
Labels: enhancement

#8 Improve "Add New Host" dialog
  frontend/components/config/EnrollSecretTable/EnrollSecretTable.jsx
  frontend/components/hosts/AddHostModal/AddHostModal.jsx
  frontend/components/hosts/AddHostModal/_styles.scss
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.tests.jsx
  tools/osquery/kolide.crt
  tools/osquery/kolide.key
Labels: enhancement

#14 Update URLs and branding in readme
  README.md
Labels: documentation

#17 Fix regression creating packs
  server/datastore/datastore_packs_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/packs.go
Labels: bug

#22 Update Slack channel names
  docs/README.md
  docs/development/release.md
  docs/infrastructure/faq.md
Labels: documentation

#18 Changelog for 3.3.0 release
  CHANGELOG.md
Labels: documentation

#26 Add transition note to readme
  README.md
Labels: documentation

#31 Include fleetctl binary archives in release
  Makefile
  docs/development/release.md
Labels: documentation

#35 Fix markdown documentation links
  .github/workflows/docs.yml
  .github/workflows/markdown-link-check-config.json
  CHANGELOG.md
  docs/development/release.md
  docs/infrastructure/fleet-on-centos.md
  docs/infrastructure/fleet-on-ubuntu.md
  frontend/README.md
Labels: documentation

#33 Add dev infrastructure and docs for Prometheus monitoring
  docker-compose.yml
  docs/infrastructure/README.md
  docs/infrastructure/faq.md
  docs/infrastructure/monitoring-alerting.md
  server/service/handler.go
  tools/app/prometheus.yml
Labels: documentation

#37 Allow @ character in usernames
  server/service/service_users_test.go
  server/service/validation_users.go
Labels: bug

#40 Fix fleetctl Windows issues
  cmd/fleetctl/api.go
  cmd/fleetctl/config.go
  server/service/client.go
Labels: bug

#45 Add debug endpoints and associated fleetctl commands
  cmd/fleet/serve.go
  cmd/fleetctl/debug.go
  cmd/fleetctl/flags.go
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/get.go
  server/service/client_debug.go
  server/service/debug_handler.go
  server/service/debug_handler_test.go
Labels: enhancement

#50 Fix unexpected print of migration status warning
  server/datastore/mysql/migrations/data/20181119180000_Placeholder.go
Labels: bug

#51 MVP of fleetctl preview command
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/preview.go
Labels: enhancement

#52 Add fleetctl installer for NPM
  docs/development/release.md
  tools/fleetctl-npm/.gitignore
  tools/fleetctl-npm/README.md
  tools/fleetctl-npm/binary.js
  tools/fleetctl-npm/install.js
  tools/fleetctl-npm/package-lock.json
  tools/fleetctl-npm/package.json
  tools/fleetctl-npm/run.js
Labels: enhancement

#60 Improve fleetctl preview startup experience
  cmd/fleetctl/preview.go
Labels: enhancement

#63 Clean up output of JS test errors
  Makefile
  frontend/components/EmailTokenRedirect/helpers.tests.js
  frontend/components/forms/fields/SelectTargetsDropdown/SelectTargetsDropdown.jsx
  frontend/kolide/entities/labels.tests.js
  frontend/pages/RegistrationPage/Breadcrumbs/Breadcrumbs.tests.jsx
  frontend/pages/RegistrationPage/RegistrationPage.tests.jsx
  frontend/pages/queries/QueryPage/QueryPage.jsx
  frontend/redux/nodes/auth/actions.tests.js
  frontend/test/reporter.js
  package.json
  yarn.lock
Labels: development infrastructure

#71 Update nav layout and styles. Cleanup unused css.
  frontend/components/buttons/Button/_styles.scss
  frontend/components/side_panels/SiteNavHeader/SiteNavHeader.jsx
  frontend/components/side_panels/SiteNavHeader/UserMenu.jsx
  frontend/components/side_panels/SiteNavHeader/_styles.scss
  frontend/components/side_panels/SiteNavSidePanel/SiteNavSidePanel.jsx
  frontend/components/side_panels/SiteNavSidePanel/_styles.scss
  frontend/components/side_panels/SiteNavSidePanel/navItems.js
  frontend/components/side_panels/UserMenu/UserMenu.jsx
  frontend/components/side_panels/UserMenu/_styles.scss
  frontend/components/side_panels/UserMenu/index.js
  frontend/layouts/CoreLayout/CoreLayout.jsx
  frontend/layouts/CoreLayout/_styles.scss
Labels: spiffier

#72 Update host side panel. New styles for labels.
  frontend/components/buttons/Button/_styles.scss
  frontend/components/hosts/HostDetails/HostDetails.jsx
  frontend/components/side_panels/HostSidePanel/HostSidePanel.jsx
  frontend/components/side_panels/HostSidePanel/PanelGroup/PanelGroup.jsx
  frontend/components/side_panels/HostSidePanel/PanelGroup/_styles.scss
  frontend/components/side_panels/HostSidePanel/PanelGroupItem/PanelGroupItem.jsx
  frontend/components/side_panels/HostSidePanel/PanelGroupItem/_styles.scss
  frontend/components/side_panels/HostSidePanel/_styles.scss
  frontend/components/side_panels/SecondarySidePanelContainer/_styles.scss
  frontend/kolide/helpers.js
Labels: spiffier

#73 New styles and layout for hosts page. Remove grid view.
  assets/images/no-matching-host-100x100@2x.png
  frontend/components/forms/fields/SelectTargetsDropdown/TargetDetails/TargetDetails.jsx
  frontend/components/hosts/HostContainer/HostContainer.jsx
  frontend/components/hosts/HostContainer/HostContainer.tests.jsx
  frontend/components/hosts/HostContainer/_styles.scss
  frontend/components/hosts/HostDetails/HostDetails.jsx
  frontend/components/hosts/HostDetails/HostDetails.tests.jsx
  frontend/components/hosts/HostDetails/_styles.scss
  frontend/components/hosts/HostDetails/index.js
  frontend/components/hosts/HostPagination/_style.scss
  frontend/components/hosts/HostsTable/HostsTable.jsx
  frontend/components/hosts/HostsTable/_styles.scss
  frontend/components/hosts/HostsTable/helpers.js
  frontend/components/side_panels/HostSidePanel/_styles.scss
  frontend/components/side_panels/SiteNavHeader/_styles.scss
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.tests.jsx
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/redux/nodes/components/ManageHostsPage/actions.js
  frontend/redux/nodes/components/ManageHostsPage/reducer.js
  frontend/redux/nodes/components/ManageHostsPage/reducer.tests.js
  frontend/styles/global/_global.scss
  frontend/styles/var/padding.scss
Labels: spiffier
