Repository fleetdm/fleet, pull requests merged in 2021-09, with the labels that each got.

#1881 Move permanent images archive to website repo
  website/assets/images/permanent/README.md
  website/assets/images/permanent/icon-avatar-default-128x128@2x.png
Labels: #website

#1907 Remove unneeded target=_blank
  website/views/pages/pricing.ejs
Labels: #website

#1880 FleetUI: Update Avatar component
  assets/images/icon-avatar-default-128x128@2x.png
  changes/1861-replace-default-avatar
  cypress/integration/all/app/queryflow.spec.ts
  cypress/integration/all/sessions/sessions.spec.ts
  cypress/integration/all/sessions/sso.spec.ts
  cypress/integration/core/maintainer.spec.ts
  frontend/components/Avatar/Avatar.tsx
  frontend/components/Avatar/_styles.scss
  frontend/fleet/helpers.ts
  frontend/utilities/constants.ts
  website/assets/images/permanent/README.md
  website/assets/images/permanent/icon-avatar-default-128x128-2x.png
Labels: #spiffier, :frontend dev (core platform), #core

#1922 Update release process documentation in the Handbook
  handbook/release-process.md
Labels: :improve handbook

#1938 Update email template image links
  changes/1927-email-template-images
  server/mail/templates/change_email_confirmation.html
  server/mail/templates/invite_token.html
  server/mail/templates/password_reset.html
  server/mail/templates/smtp_setup.html
  server/service/service.go
  website/assets/images/permanent/fleet-logo-blue-118x41@2x.png
  website/assets/images/permanent/fleet-mark-color-40x40@2x.png
  website/assets/images/permanent/slack-logo-41x40@2x.png
  website/assets/images/permanent/twitter-logo-50x40@2x.png
Labels: bug

#1935 Hide enroll secret for team observer
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/_styles.scss
Labels: bug

#1936 Use replace instead of push for host table changes
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: bug

#2051 Hide remediation field for query detail pages on website
  website/assets/js/pages/query-detail.page.js
  website/scripts/build-static-content.js
  website/views/pages/query-detail.ejs
Labels: #website

#2082 Add page titles and descriptions to fleetdm.com
  website/config/routes.js
  website/views/layouts/layout.ejs
Labels: #website

#2084 Add JSON syntax highlighting Rest API docs page
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation, #website

#2010 Add clickable anchor links in fleetdm.com/docs
  website/api/helpers/strings/to-html.js
  website/assets/images/icon-link-16x16@2x.png
  website/assets/js/pages/docs/basic-documentation.page.js
  website/assets/styles/pages/docs/basic-documentation.less
Labels: :improve documentation, #website, :frontend dev (website)

#2092 Update SSO configuration docs
  .github/workflows/markdown-link-check-config.json
  docs/2-Deploying/2-Configuration.md
Labels: :improve documentation

#2083 Implement redirect in view-basic-documentation
  website/api/controllers/docs/view-basic-documentation.js
Labels: :improve documentation, #website

#2143 Increase timeout for golangci-lint
  .github/workflows/golangci-lint.yml
Labels: #contributor experience

#2153 Add Policies feature to permissions documentation
  docs/01-Using-Fleet/09-Permissions.md
Labels: :improve documentation

#2167 Fix tagging branch name in development Docker publish
  .github/workflows/goreleaser-snapshot-fleet.yaml
Labels: #contributor experience

#2171 Add --tag flag to fleetctl preview
  changes/preview-tag
  cmd/fleetctl/preview.go
Labels: #fleetctl preview

#2177 Prepare for 4.3.1 release
  CHANGELOG.md
  changes/2107-sidebar-style
  changes/2112-flaky-observer-hosts
  changes/add-jitter-percent
  changes/ensure-only-one-row-disk-space
  changes/improve-speed-of-migration
  changes/issue-1512-filter-queries
  changes/issue-1893-team-policies
  changes/issue-1950-logging-filesystem-fail-early
  changes/issue-1963-vulnerabilities-no-sync
  changes/issue-1964-list-software
  changes/issue-1969-redis-config
  changes/issue-2062-team-maintainer-run-new
  changes/preview-tag
  changes/remove-fk-label-membership
  changes/skip-save-users-if-disabled
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/deploy/terraform-aws-fargate/database.tf
  tools/deploy/terraform-aws-fargate/variables.tf
  tools/docker-fleetctl-awscli/Dockerfile
  tools/fleetctl-npm/package.json
Labels: :improve documentation

#2178 Always check doc links in CI
  .github/workflows/docs.yml
Labels: :improve documentation, #contributor experience

#2186 No clicking on new query
  frontend/components/forms/queries/QueryForm/QueryForm.tsx
Labels: #spiffier

#2203 Fixes to fleetctl debug archive docs
  docs/01-Using-Fleet/06-Monitoring-Fleet.md
Labels: :improve documentation

#2080 Schedules Page: Surface all teams schedule on team schedule page
  changes/issue-1894-surface-inherited-queries
  cypress/integration/all/app/queryflow.spec.ts
  cypress/integration/free/observer.spec.ts
  cypress/integration/premium/teamflow.spec.ts
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.jsx
  frontend/pages/schedule/ManageSchedulePage/ManageSchedulePage.tsx
  frontend/pages/schedule/ManageSchedulePage/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleListWrapper.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleTableConfig.tsx
Labels: :frontend dev (core platform)

#2234 Update pull request template
  .github/pull_request_template.md
Labels: #contributor experience

#2199 Improve examples and API documentation for managing teams with `fleetctl`
  docs/01-Using-Fleet/03-REST-API.md
  docs/01-Using-Fleet/configuration-files/multi-file-configuration/team.yml
Labels: :improve documentation, #contributor experience

#2279 Update observer_can_run display value
  changes/issue-2241-observer-can-run-bool
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/QueriesTableConfig.tsx
Labels: #spiffier

#2276 Update changelog for 4.3.2 release
  CHANGELOG.md
  changes/1839-create-user-error
  changes/add-policy-updated-at
  changes/cache-app-config
  changes/issue-1984-label-count-on-edit
  changes/issue-2078-enter-submits-create-team
  changes/issue-2130-replace-contenteditables
  changes/issue-2160-straighten-permissions-around-policies
  changes/issue-2201-global-maintainer-create-query
  changes/issue-2206-query-aselect-all
  changes/issue-2207-query-form-info
  changes/issue-2269-query-results
  changes/reduce-sql-queries-per-host
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/fleetctl-npm/package.json
Labels: :improve documentation
