Repository fleetdm/fleet, pull requests merged in 2021-05, with the labels that each got.

#708 Add package-lock.json to .gitignore
  .gitignore
Labels: development infrastructure

#701 Fix admin setup
  server/service/endpoint_setup.go
Labels: teams/RBAC

#696 Add agent options on a per-team basis
  server/datastore/mysql/migrations/tables/20210428163822_TeamAgentOptions.go
  server/datastore/mysql/teams.go
  server/kolide/teams.go
  server/service/service_teams.go
Labels: teams/RBAC

#718 Update documentation on size of Fleet deployments
  docs/1-Using-Fleet/FAQ.md
Labels: documentation

#720 Fix for flaky teams e2e test
  cypress/integration/app/teamflow.spec.ts
Labels: refactoring, teams/RBAC

#717 Bring Orbit docs into Fleet docs and add FAQ section
  CHANGELOG.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/4-Osquery-logs.md
  docs/1-Using-Fleet/6-Security-best-practices.md
  docs/1-Using-Fleet/7-Updating-Fleet.md
  docs/1-Using-Fleet/FAQ.md
  docs/2-Orbit-osquery/README.md
  docs/3-Deployment/1-Installation.md
  docs/3-Deployment/2-Configuration.md
  docs/3-Deployment/3-Adding-hosts.md
  docs/3-Deployment/4-Example-deployment-scenarios.md
  docs/3-Deployment/4-fleetctl-agent-updates.md
  docs/3-Deployment/FAQ.md
  docs/3-Deployment/README.md
  docs/4-Contribution/1-Building-Fleet.md
  docs/4-Contribution/2-Testing.md
  docs/4-Contribution/3-Migrations.md
  docs/4-Contribution/4-Committing-Changes.md
  docs/4-Contribution/5-Releasing-Fleet.md
  docs/4-Contribution/FAQ.md
  docs/4-Contribution/README.md
  docs/README.md
  frontend/README.md
  frontend/components/hosts/AddHostModal/AddHostModal.jsx
  tools/backup_db/README.md
  website/config/routes.js
Labels: documentation, orbit

#721 Add waits in Teams e2e test
  cypress/integration/app/activateuser.spec.ts
  cypress/integration/app/teamflow.spec.ts
Labels: refactoring, teams/RBAC

#726 Add to Using Fleet FAQ and add documentation section to CONTRIBUTING.md
  CONTRIBUTING.md
  docs/1-Using-Fleet/FAQ.md
Labels: documentation

#731 Add relative markdown links to teams branch
  CHANGELOG.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/FAQ.md
  frontend/README.md
Labels: documentation, teams/RBAC

#735 Implement storage of scheduled query statistics
  server/datastore/datastore.go
  server/datastore/datastore_hosts.go
  server/datastore/datastore_scheduled_queries.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/migrations/tables/20210506095025_AddScheduledQueryStats.go
  server/datastore/mysql/scheduled_queries.go
  server/kolide/hosts.go
  server/kolide/packs.go
  server/kolide/scheduled_queries.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/test/new_objects.go
Labels: enhancement

#715 Update website styling
  website/assets/styles/bootstrap-overrides.less
  website/assets/styles/layout.less
  website/assets/styles/pages/get-started.less
  website/assets/styles/pages/homepage.less
  website/assets/styles/pages/pricing.less
  website/views/layouts/layout.ejs
  website/views/pages/get-started.ejs
  website/views/pages/homepage.ejs
  website/views/pages/pricing.ejs
Labels: website

#742 Add description to returned query stats
  server/datastore/mysql/hosts.go
  server/kolide/scheduled_queries.go
Labels: enhancement

#737 website-add-jobs-link
  website/assets/styles/layout.less
  website/views/layouts/layout.ejs
Labels: website

#712 GCP pubsub log destination: Take advantage of new filtering capabilities (Allow copying top-level fields and decorations into Pub/Sub attributes)
  docs/3-Deployment/2-Configuration.md
  server/config/config.go
  server/logging/logging.go
  server/logging/pubsub.go
Labels: enhancement, gcp pubsub

#695 Prevent modify user to include global and team roles
  server/kolide/users.go
  server/service/endpoint_setup.go
  server/service/service_users.go
Labels: teams/RBAC

#757 Implement API endpoints for Teams agent options
  server/kolide/teams.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_teams.go
  server/service/transport_teams.go
Labels: teams/RBAC

#759 Resolve lint errors and JS unit tests in teams branch
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/components/AddHostsModal/index.ts
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.tests.jsx
  frontend/pages/hosts/ManageHostsPage/components/AddHostModal/AddHostModal.jsx
Labels: refactoring, teams/RBAC

#761 Add support for bulk transfer of hosts for team
  server/datastore/datastore.go
  server/datastore/datastore_teams.go
  server/datastore/mysql/teams.go
  server/kolide/teams.go
  server/mock/datastore_teams.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_teams.go
  server/service/transport_teams.go
Labels: teams/RBAC

#767 Add refetch host API
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/mysql/hosts.go
  server/datastore/mysql/migrations/tables/20210513115729_RefetchHostDetail.go
  server/kolide/hosts.go
  server/service/endpoint_hosts.go
  server/service/handler.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/service/transport_hosts.go
Labels: enhancement

#749 Convert standard query library to YAML format
  .github/workflows/markdown-link-check-config.json
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/configuration-files/README.md
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-deployment.yml
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-migrations.yml
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-service.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/agent-options.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/enroll-secrets.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/labels.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/packs/osquery-monitoring.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/queries.yml
  docs/1-Using-Fleet/configuration-files/single-file-configuration.yml
  docs/1-Using-Fleet/standard-query-library/README.md
  docs/1-Using-Fleet/standard-query-library/standard-query-library.yml
  docs/3-Deployment/4-Example-deployment-scenarios.md
  handbook/queries/README.md
  handbook/queries/get-installed-safari-extensions.md
Labels: query library

#776 Fix foreign key cascade for query stats table
  server/datastore/mysql/migrations/tables/20210506095025_AddScheduledQueryStats.go
Labels: bug

#778 Move and refactor host team transfer endpoint
  server/datastore/datastore.go
  server/datastore/datastore_hosts.go
  server/datastore/datastore_teams.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/teams.go
  server/kolide/hosts.go
  server/kolide/teams.go
  server/mock/datastore_hosts.go
  server/mock/datastore_teams.go
  server/service/endpoint_hosts.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_hosts.go
  server/service/service_teams.go
  server/service/transport_hosts.go
  server/service/transport_teams.go
Labels: teams/RBAC

#777 Add "observer can run" to query objects
  server/datastore/datastore_queries.go
  server/datastore/mysql/migrations/tables/20210517112751_TeamsObserverQueries.go
  server/datastore/mysql/queries.go
  server/kolide/queries.go
Labels: teams/RBAC

#779 Add bash script that creates 3 teams and 12 users to /tools/api
  docs/3-Contribution/2-Testing.md
  tools/api/README.md
  tools/api/fleet/me
  tools/api/fleet/packs/create
  tools/api/fleet/packs/list
  tools/api/fleet/packs/scheduled
  tools/api/fleet/queries/create
  tools/api/fleet/queries/list
  tools/api/fleet/schedule/add_query_to_pack
  tools/api/fleet/schedule/delete_scheduled_query
  tools/api/fleet/teams/create
Labels: development infrastructure, teams/RBAC

#770 Add manual QA documentation to handbook
  handbook/manual-qa.md
Labels: documentation

#781 Include team name in host API responses
  server/datastore/mysql/hosts.go
  server/kolide/hosts.go
Labels: teams/RBAC

#713 Add icon button styles and edit TableContainer to support styles
  assets/images/icon-edit-columns-16x12@2x.png
  assets/images/icon-edit-columns-20x20@2x.png
  assets/images/icon-pencil-14x14@2x.png
  assets/images/icon-trash-14x14@2x.png
  frontend/components/TableContainer/TableContainer.tsx
  frontend/components/TableContainer/_styles.scss
  frontend/components/buttons/Button/_styles.scss
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/TeamDetailsWrapper.tsx
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/_styles.scss
  frontend/pages/admin/TeamManagementPage/TeamManagementPage.tsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: spiffier, teams/RBAC

#790 Add Loom demo for creating teams seed data
  docs/3-Contribution/2-Testing.md
Labels: documentation, teams/RBAC

#791 Add persistent fetching to Host details page and edit query modal styles
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/SelectQueryModal/SelectQueryModal.jsx
  frontend/pages/hosts/HostDetailsPage/SelectQueryModal/_styles.scss
  frontend/pages/hosts/HostDetailsPage/_styles.scss
Labels: frontend, spiffier

#799 Disable "Refetch" button for offline hosts
  frontend/components/LoginRoutes/_styles.scss
  frontend/components/packs/PacksList/Row/_styles.scss
  frontend/components/queries/QueriesList/QueriesListRow/_styles.scss
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/_styles.scss
  frontend/components/side_panels/HostSidePanel/PanelGroupItem/_styles.scss
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/styles/global/_global.scss
Labels: frontend, spiffier

#801 Add instructions for resolving failed website deploy action to /handbook
  handbook/README.md
Labels: documentation

#802 Upgrade dependencies and remove replace directive
  go.mod
  go.sum
Labels: refactoring

#808 Update Orbit packaging documentation
  docs/2-Orbit-osquery/README.md
Labels: documentation

#810 Stub out licensing API
  cmd/fleet/serve.go
  ee/licensing/licensing.go
  server/config/config.go
  server/kolide/app.go
  server/service/endpoint_appconfig.go
  server/service/service.go
  server/service/service_appconfig.go
  server/service/util_test.go
Labels: teams/RBAC

#803 Changed cursor:pointer to cursor:unset on Get started dropdown.
  website/assets/styles/layout.less
Labels: website

#819 Fix capitalization on "Select pack targets"
  frontend/components/forms/packs/EditPackForm/EditPackForm.jsx
Labels: frontend

#823 Fix setting observer_can_run in query API
  server/kolide/queries.go
  server/service/service_queries.go
Labels: bug, teams/RBAC

#824 Include null team name in teams response
  server/kolide/hosts.go
Labels: teams/RBAC

#829 Corrections in configuration documentation
  docs/3-Deployment/2-Configuration.md
Labels: documentation

#844 Add note about user passwords generated by teams script
  docs/4-Contribution/2-Testing.md
Labels: development infrastructure, documentation

#847 Cleanup live query store for orphaned query
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: bug

#850 Filter query page API responses based on team membership
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/datastore_hosts.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_targets.go
  server/datastore/inmem/hosts.go
  server/datastore/inmem/labels.go
  server/datastore/inmem/targets.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/datastore/mysql/targets.go
  server/kolide/hosts.go
  server/kolide/labels.go
  server/kolide/targets.go
  server/kolide/teams.go
  server/mock/datastore_hosts.go
  server/mock/datastore_labels.go
  server/mock/datastore_targets.go
  server/service/endpoint_packs.go
  server/service/endpoint_targets.go
  server/service/service_campaigns.go
  server/service/service_osquery_test.go
  server/service/service_targets.go
  server/service/service_targets_test.go
  server/test/comparisons.go
  tools/api/fleet/teams/create
Labels: teams/RBAC

#861 Fix host count for list teams
  server/datastore/datastore.go
  server/datastore/datastore_teams.go
  server/datastore/mysql/teams.go
Labels: bug, teams/RBAC

#863 Refactor usage of null values in Teams models
  server/datastore/datastore_hosts.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_packs.go
  server/datastore/datastore_scheduled_queries.go
  server/datastore/datastore_targets.go
  server/datastore/datastore_users.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/kolide/hosts.go
  server/kolide/users.go
  server/ptr/ptr.go
  server/service/service_agent_options.go
  server/service/service_agent_options_test.go
  server/service/service_appconfig_test.go
  server/service/service_invites_test.go
  server/service/service_targets_test.go
  server/service/service_users.go
  server/service/service_users_test.go
  server/service/util_test.go
Labels: refactoring, teams/RBAC

#864 Refactor struct slices for consistent pointer use
  cmd/fleetctl/get.go
  cmd/fleetctl/goquery.go
  server/datastore/datastore_labels.go
  server/datastore/inmem/labels.go
  server/datastore/mysql/labels.go
  server/kolide/app.go
  server/kolide/hosts.go
  server/kolide/labels.go
  server/kolide/targets.go
  server/mock/datastore_labels.go
  server/service/client_targets.go
  server/service/endpoint_campaigns.go
  server/service/endpoint_hosts.go
  server/service/endpoint_labels.go
  server/service/endpoint_targets.go
  server/service/service_campaigns.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
  server/service/service_labels.go
  server/service/service_targets.go
  server/service/service_targets_test.go
Labels: refactoring

#866 Implement add hosts to team by filters API
  docs/1-Using-Fleet/3-REST-API.md
  server/kolide/hosts.go
  server/service/endpoint_hosts.go
  server/service/handler.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
  server/service/transport_hosts.go
Labels: teams/RBAC

#800 Website query library styling
  website/assets/styles/mixins-and-variables/colors.less
  website/assets/styles/pages/query-detail.less
  website/views/pages/query-detail.ejs
Labels: website

#871 Only run markdown link check when markdown files are edited
  .github/workflows/docs.yml
Labels: development infrastructure

#875 Split host additional into separate table
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/datastore_hosts.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/migrations/tables/20210526113559_MoveHostAdditionalToSeparateTable.go
  server/kolide/hosts.go
  server/mock/datastore_hosts.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: breaking, enhancement, refactoring

#874 Add Release process document to /handbook
  handbook/README.md
  handbook/release-process.md
Labels: documentation

#876 Update live query and targets APIs for Teams
  docs/1-Using-Fleet/3-REST-API.md
  server/kolide/campaigns.go
  server/kolide/targets.go
  server/service/client_live_query.go
  server/service/client_targets.go
  server/service/endpoint_campaigns.go
  server/service/endpoint_packs.go
  server/service/endpoint_targets.go
  server/service/logging_campaigns.go
  server/service/service_campaigns.go
  server/service/service_osquery_test.go
  server/service/service_queries.go
  server/service/service_targets.go
  server/service/service_targets_test.go
  server/service/transport_targets_test.go
Labels: teams/RBAC

#880 Add support for Teams in targets and live queries
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/datastore.go
  server/datastore/datastore_campaigns.go
  server/datastore/datastore_targets.go
  server/datastore/datastore_teams.go
  server/datastore/inmem/campaigns.go
  server/datastore/inmem/targets.go
  server/datastore/mysql/campaigns.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/datastore/mysql/targets.go
  server/datastore/mysql/teams.go
  server/kolide/campaigns.go
  server/kolide/targets.go
  server/kolide/teams.go
  server/mock/datastore_campaigns.go
  server/mock/datastore_targets.go
  server/mock/datastore_teams.go
  server/service/client_targets.go
  server/service/endpoint_campaigns.go
  server/service/endpoint_packs.go
  server/service/endpoint_targets.go
  server/service/logging_campaigns.go
  server/service/service_campaigns.go
  server/service/service_osquery_test.go
  server/service/service_targets.go
  server/service/service_targets_test.go
  server/service/service_teams.go
  server/service/transport_targets_test.go
Labels: enhancement, refactoring, teams/RBAC

#883 Move community project links into Example deployment scenario docs
  README.md
  docs/3-Deployment/4-Example-deployment-scenarios.md
Labels: documentation

#878 Add link to release blog post in Software inventory documentation
  docs/3-Deployment/2-Configuration.md
Labels: documentation

#887 Implement query detail page for standard query library
  website/assets/images/lightbulb-blue-24x24@2x.png
  website/assets/styles/pages/query-detail.less
  website/views/pages/query-detail.ejs
Labels: website

#892 Add robots noindex to frontend HTML head
  frontend/templates/react.ejs
Labels: enhancement, frontend

#897 In 3-Deployment/2-Configuration add note about mitigating DoS attacks
  docs/3-Deployment/2-Configuration.md
Labels: documentation

#891 Implement query-library page for fleetdm.com
  website/assets/js/pages/query-detail.page.js
  website/assets/js/pages/query-library.page.js
  website/assets/styles/pages/query-library.less
  website/views/pages/query-detail.ejs
  website/views/pages/query-library.ejs
Labels: website

#903 Refactor enroll secrets to support Teams
  cmd/fleetctl/get.go
  cmd/fleetctl/preview.go
  docs/1-Using-Fleet/3-REST-API.md
  frontend/components/config/EnrollSecretTable/EnrollSecretTable.jsx
  frontend/components/config/EnrollSecretTable/EnrollSecretTable.tests.jsx
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.tests.jsx
  server/datastore/datastore.go
  server/datastore/datastore_app.go
  server/datastore/datastore_hosts.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_targets.go
  server/datastore/inmem/hosts.go
  server/datastore/mysql/app_configs.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/migrations/tables/20210527151852_TeamsEnrollSecrets.go
  server/datastore/mysql/teams.go
  server/kolide/app.go
  server/kolide/hosts.go
  server/kolide/teams.go
  server/mock/datastore_appconfig.go
  server/mock/datastore_hosts.go
  server/mock/datastore_teams.go
  server/service/endpoint_setup.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_appconfig.go
  server/service/service_appconfig_test.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/service/service_teams.go
  server/service/transport_teams.go
Labels: --enhancement, teams/RBAC
