Repository fleetdm/fleet, pull requests merged in 2021-03, with the labels that each got.

#364 Task/finishing ts in data table components
  .eslintrc.js
  frontend/components/buttons/Button/Button.tsx
  frontend/interfaces/host.ts
  frontend/interfaces/label.ts
  frontend/interfaces/pack.ts
  frontend/interfaces/query.ts
  frontend/interfaces/scheduled_query.ts
  frontend/kolide/helpers.ts
  frontend/pages/hosts/ManageHostsPage/components/HeaderCell/HeaderCell.tsx
  frontend/pages/hosts/ManageHostsPage/components/HostContainer/HostTableConfig.tsx
  frontend/pages/hosts/ManageHostsPage/components/LinkCell/LinkCell.tsx
  frontend/pages/hosts/ManageHostsPage/components/StatusCell/StatusCell.tsx
  frontend/pages/hosts/ManageHostsPage/components/TextCell/TextCell.tsx
  frontend/router/paths.ts
  frontend/router/url_prefix.js
  frontend/router/url_prefix.ts
  package.json
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: development infrastructure, frontend, refactoring

#385 Remove flaky log rotation test
  server/service/service_test.go
Labels: development infrastructure

#381 Migrate tests to GitHub Actions and add E2E testing
  .circleci/config.yml
  .github/workflows/test.yml
  Makefile
  cypress/integration/login/logging_in.spec.ts
  docs/3-Contribution/2-Testing.md
Labels: development infrastructure

#386 Add cleanup before make generate step
  Makefile
Labels: development infrastructure

#389 Remove second call to docker-compose in CI tests
  .github/workflows/test.yml
Labels: development infrastructure

#403 On fleetdm.com, add asterisks for features coming in 2021
  website/views/pages/homepage.ejs
Labels: website

#394 Fix live query UI expanded view
  frontend/components/queries/QueryResultsTable/_styles.scss
Labels: bug, frontend

#411 In REST API documentation, fix run queries endpoints
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#414 Bump development docker-compose Redis to version 5
  docker-compose.yml
Labels: development infrastructure

#395 Add documentation for websocket endpoints
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#417 Make host identifier configurable within Fleet
  cmd/fleet/serve.go
  docs/2-Deployment/2-Configuration.md
  server/config/config.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: enhancement

#418 Make enrollment cooldown configurable
  docs/2-Deployment/2-Configuration.md
  server/config/config.go
  server/datastore/datastore_hosts_test.go
  server/datastore/datastore_labels_test.go
  server/datastore/datastore_targets_test.go
  server/datastore/inmem/hosts.go
  server/datastore/mysql/hosts.go
  server/kolide/hosts.go
  server/mock/datastore_hosts.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: enhancement

#420 Fix flapping IP addresses
  server/datastore/mysql/hosts.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: bug

#425 Front end style and experience fixes
  frontend/components/flash_messages/FlashMessage/_styles.scss
  frontend/pages/admin/AppSettingsPage/AppSettingsPage.jsx
  frontend/pages/admin/AppSettingsPage/AppSettingsPage.tests.jsx
  frontend/pages/admin/OsqueryOptionsPage/OsqueryOptionsPage.jsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/_styles.scss
Labels: spiffier

#426 Update osquery version options
  frontend/components/forms/ConfigurePackQueryForm/ConfigurePackQueryForm.jsx
Labels: frontend

#429 Edit API docs for `/queries/run_by_names` endpoint. Edit fleetctl docs
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#448 Improve E2E testing and test documentation
  .github/workflows/test.yml
  Makefile
  cypress.json
  cypress/integration/login/logging_in.spec.ts
  docs/3-Contribution/2-Testing.md
Labels: development infrastructure, documentation

#438 In REST API docs, fix queries/run_by_names endpoint
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#457 Improvements to fleetdm.com home page
  website/views/pages/homepage.ejs
Labels: website

#450 Refactor cypress tests and expand testing
  .gitignore
  cypress/integration/app/hosts.spec.ts
  cypress/integration/login/logging_in.spec.ts
  cypress/integration/sessions/sessions.spec.ts
  cypress/integration/setup/setup.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  frontend/components/forms/RegistrationForm/ConfirmationPage/ConfirmationPage.jsx
  package.json
  tsconfig.json
  yarn.lock
Labels: frontend

#458 Update website README with local usage instructions
  website/README.md
Labels: documentation, website

#461 On fleetdm.com, add categories and additional items to roadmap
  website/views/pages/homepage.ejs
Labels: website

#471 Upgrade fleetctl github.com/urfave/cli to v2
  cmd/fleetctl/api.go
  cmd/fleetctl/apply.go
  cmd/fleetctl/config.go
  cmd/fleetctl/convert.go
  cmd/fleetctl/debug.go
  cmd/fleetctl/delete.go
  cmd/fleetctl/flags.go
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/get.go
  cmd/fleetctl/goquery.go
  cmd/fleetctl/login.go
  cmd/fleetctl/logout.go
  cmd/fleetctl/preview.go
  cmd/fleetctl/query.go
  cmd/fleetctl/setup.go
  cmd/fleetctl/user.go
  go.mod
  go.sum
Labels: refactoring

#480 Backup and restore for development database
  .gitignore
  docs/3-Contribution/2-Testing.md
  tools/backup_db/README.md
  tools/backup_db/backup.sh
  tools/backup_db/restore.sh
Labels: development infrastructure

#482 Add note to update the #fleet channel's topic in Releasing Fleet documentation
  docs/3-Contribution/5-Releasing-Fleet.md
Labels: documentation

#486 Speed up labels MySQL tests
  server/datastore/datastore_labels_test.go
Labels: development infrastructure

#488 Test and correct semantics for MySQL withRetryTxx
  go.mod
  go.sum
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
Labels: refactoring

#490 Add search for list users endpoint
  server/datastore/datastore_hosts_test.go
  server/datastore/datastore_test.go
  server/datastore/datastore_users_test.go
  server/datastore/mysql/users.go
  server/kolide/app.go
  server/kolide/hosts.go
  server/service/transport.go
Labels: refactoring, teams/RBAC

#483 Initial work on user team information storage and retrieval
  server/datastore/datastore_teams_test.go
  server/datastore/datastore_test.go
  server/datastore/datastore_users_test.go
  server/datastore/mysql/migrations/tables/20210315111056_CreateTeamsTables.go
  server/datastore/mysql/teams.go
  server/datastore/mysql/users.go
  server/kolide/datastore.go
  server/kolide/hosts.go
  server/kolide/service.go
  server/kolide/teams.go
  server/kolide/users.go
  server/mock/datastore.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_teams.go
  server/service/service_users.go
  server/service/transport_teams.go
Labels: teams/RBAC

#492 Fix teams JSON key
  server/kolide/users.go
Labels: teams/RBAC

#493 Save global role for users
  server/datastore/mysql/users.go
Labels: teams/RBAC

#496 Log all errors regardless of log level
  server/service/logging.go
Labels: bug

#495 Improvements to fleetctl preview
  cmd/fleetctl/preview.go
Labels: spiffier

#509 Fix broken anchor links in documentation
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/5-Monitoring-Fleet.md
  docs/1-Using-Fleet/6-Security-best-practices.md
  docs/1-Using-Fleet/FAQ.md
  docs/2-Deployment/2-Configuration.md
  docs/2-Deployment/FAQ.md
  docs/3-Contribution/1-Building-Fleet.md
  docs/3-Contribution/2-Testing.md
  docs/3-Contribution/FAQ.md
Labels: documentation

#512 Upgrade go-bindata to maintained github.com/kevinburke/go-bindata
  Makefile
  go.mod
  go.sum
  tools.go
Labels: development infrastructure, refactoring

#513 Improve build documentation
  docs/3-Contribution/1-Building-Fleet.md
Labels: development infrastructure, documentation

#508 Make fleetctl preview available over HTTP
  README.md
  cmd/fleetctl/preview.go
Labels: spiffier

#517 Add top navigation, add new assets, and edit text on fleetdm.com
  website/assets/images/deploy-aws-99x60@2x.png
  website/assets/images/deploy-google-cloud-75x60@2x.png
  website/assets/images/deploy-kubernetes-64x62@2x.png
  website/assets/images/github-mark-blue-24x24@2x.png
  website/assets/images/github-mark-white-24x24@2x.png
  website/assets/images/graphic-log-location-1024x469@2x.png
  website/assets/images/icon-close-16x16@2x.png
  website/assets/images/icon-hamburger-16x14@2x.png
  website/assets/images/logo-blue-162x92@2x.png
  website/assets/images/logo-white-162x92@2x.png
  website/assets/images/os-apple-52x56@2x.png
  website/assets/images/os-centos-37x36@2x.png
  website/assets/images/os-centos-60x56@2x.png
  website/assets/images/os-linux-32x36@2x.png
  website/assets/images/os-linux-50x56@2x.png
  website/assets/images/os-macos-31x35@2x.png
  website/assets/images/os-ubuntu-34x36@2x.png
  website/assets/images/os-ubuntu-54x56@2x.png
  website/assets/images/os-windows-37x36@2x.png
  website/assets/images/os-windows-59x56@2x.png
  website/assets/styles/bootstrap-overrides.less
  website/assets/styles/layout.less
  website/assets/styles/mixins-and-variables/typography.css
  website/assets/styles/mixins-and-variables/typography.less
  website/assets/styles/pages/homepage.less
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/homepage.ejs
Labels: website

#525 Add new screenshot to documentation
  docs/images/add-new-host-modal.png
Labels: documentation

#534 Fix default typo in host identifier docs
  docs/2-Deployment/2-Configuration.md
Labels: documentation

#533 Prevent user enumeration
  cmd/fleetctl/login.go
  cypress/integration/sessions/sessions.spec.ts
  server/service/client_errors.go
  server/service/client_sessions.go
  server/service/endpoint_middleware.go
  server/service/endpoint_sessions.go
  server/service/endpoint_users.go
  server/service/logging.go
  server/service/service_errors.go
  server/service/service_sessions.go
  server/service/service_users.go
  server/service/transport_error.go
Labels: enhancement

#535 Daily deploy - 2021.03.24
  website/assets/images/fleetctl-800x460@2x.png
  website/assets/images/fleetctl-900x580@2x.png
  website/assets/images/logo-white-162x92@2x.png
  website/views/pages/homepage.ejs
Labels: website

#538 Document delve debug process
  docs/3-Contribution/1-Building-Fleet.md
Labels: development infrastructure, documentation

#542 Adjust UI layout styles and fix empty state on "Hosts" page
  frontend/components/flash_messages/FlashMessage/_styles.scss
  frontend/components/flash_messages/PersistentFlash/_styles.scss
  frontend/layouts/CoreLayout/_styles.scss
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/pages/hosts/ManageHostsPage/components/HostContainer/_styles.scss
  frontend/pages/packs/AllPacksPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/_styles.scss
  frontend/styles/global/_global.scss
  frontend/styles/var/_global.scss
Labels: spiffier

#516 Initial implementation of agent update management
  cmd/fleetctl/fleetctl.go
  docs/2-Deployment/4-fleetctl-agent-updates.md
  docs/2-Deployment/README.md
  ee/fleetctl/updates.go
  go.mod
  go.sum
Labels: enhancement, orbit

#543 Add rate-limiting to login and password reset
  cmd/fleet/serve.go
  go.mod
  go.sum
  server/service/endpoint_test.go
  server/service/handler.go
  server/service/handler_test.go
  server/service/http_auth_test.go
  server/service/middleware/ratelimit/ratelimit.go
  server/service/middleware/ratelimit/ratelimit_test.go
  server/service/service_errors.go
  server/service/transport_error.go
Labels: enhancement

#549 Add version endpoint to API
  docs/1-Using-Fleet/3-REST-API.md
  server/kolide/app.go
  server/service/endpoint_appconfig.go
  server/service/handler.go
  server/service/service_appconfig.go
Labels: enhancement

#548 Prefer IPv4 in Host Details
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: enhancement

#552 Add ability to test SSO locally
  docker-compose.yml
  docs/3-Contribution/2-Testing.md
Labels: development infrastructure, documentation

#556 Add support for IdP-initiated SSO login
  .github/workflows/test.yml
  Makefile
  cypress/integration/sessions/sso.spec.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.jsx
  frontend/kolide/helpers.ts
  go.mod
  go.sum
  package.json
  server/datastore/mysql/app_configs.go
  server/datastore/mysql/migrations/tables/20210326182902_AddEnableSSOIdPLogin.go
  server/kolide/app.go
  server/service/endpoint_appconfig.go
  server/service/endpoint_sessions.go
  server/service/service_appconfig.go
  server/service/service_sessions.go
  server/service/validation_sessions.go
  server/sso/validate.go
  server/sso/validate_test.go
  tools.go
  yarn.lock
Labels: enhancement

#562 Improvements to built-in labels
  frontend/kolide/helpers.ts
  go.mod
  go.sum
  server/datastore/internal/appstate/labels.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/migrations/data/20210330130314_UpdateBuiltinLabels.go
Labels: bug, enhancement

#560 Update style on SSO login page and confirm SSO invite page
  frontend/components/forms/ConfirmSSOInviteForm/ConfirmSSOInviteForm.jsx
  frontend/components/forms/LoginForm/LoginForm.jsx
  frontend/components/forms/LoginForm/_styles.scss
  frontend/pages/ConfirmSSOInvitePage/ConfirmSSOInvitePage.jsx
  frontend/pages/ConfirmSSOInvitePage/_styles.scss
Labels: frontend, spiffier

#561 Add platform text to Queries list on "Pack" page
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.jsx
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.tests.jsx
  frontend/components/queries/ScheduledQueriesList/_styles.scss
Labels: frontend

#567 Update schema for osquery 4.7.0
  frontend/osquery_tables.json
Labels: documentation

#570 On fleetdm.com, add stubbed "Get started" page
  website/api/controllers/view-get-started.js
  website/assets/images/github-mark-24x24.svg
  website/assets/styles/importer.less
  website/assets/styles/layout.less
  website/assets/styles/pages/get-started.less
  website/config/policies.js
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/get-started.ejs
  website/views/pages/homepage.ejs
Labels: website
