Repository fleetdm/fleet, pull requests merged in 2021-12, with the labels that each got.

#3246 Update documentation for redis cluster support
  docs/02-Deploying/02-Configuration.md
Labels: :improve documentation

#3210 Fix Windows Orbit packaging with non-stable channel
  changes/fix-windows-orbit-non-stable
  orbit/pkg/packaging/windows_templates.go
Labels: #agent autoupdater, :golang dev

#3249 Configure nofiles ulimit in Terraform ECS task
  tools/terraform/ecs.tf
Labels: :improve documentation

#3270 Fix broken link in documentation
  docs/02-Deploying/FAQ.md
Labels: :improve documentation

#3206 Add wrap for SMTP connection error
  server/mail/mail.go
Labels: :backend

#3213 Update documentation for file carving
  docs/01-Using-Fleet/02-fleetctl-CLI.md
  docs/02-Deploying/03-Configuration.md
Labels: :improve documentation

#3268 Enable function-style file carving in Orbit
  orbit/pkg/osquery/flags.go
Labels: #agent autoupdater, :golang dev

#3324 Update query for users listing
  changes/update-users
  server/service/osquery_utils/queries.go
Labels: :golang dev, :backend

#3339 Increase session duration with --dev flag
  cmd/fleet/main.go
Labels: #contributor experience

#3341 Upload Cypress recordings/screenshots on E2E failure
  .github/workflows/test.yml
  cypress-free.json
  cypress-premium.json
  cypress.json
Labels: #contributor experience

#3342 Disable fail-fast for E2E test runs
  .github/workflows/test.yml
Labels: #contributor experience

#3348 API docs: Add host status webhook parameters to `PATCH /config` docs
  docs/01-Using-Fleet/03-REST-API.md
Labels: :improve documentation

#3327 Optimize requests on packs page
  changes/fix-packs-page
  cypress/integration/all/app/packflow.spec.ts
  frontend/components/forms/packs/EditPackForm/EditPackForm.tsx
  frontend/components/forms/packs/PackForm/PackForm.tsx
  frontend/interfaces/pack.ts
  frontend/pages/packs/EditPackPage/EditPackPage.tsx
  server/datastore/mysql/packs.go
  server/datastore/mysql/packs_test.go
  server/fleet/packs.go
  server/fleet/targets.go
  server/fleet/targets_test.go
Labels: bug, :frontend, :backend

#3370 Add id for anchor to testimonials div on website
  website/views/pages/homepage.ejs
Labels: :frontend dev (website)

#3404 Remove Badger DB in Orbit
  orbit/cmd/orbit/orbit.go
Labels: #agent autoupdater, :golang dev

#3411 Add fleetdm.com/jobs route
  website/config/routes.js
Labels: :frontend dev (website)

#3414 Update GitHub goreleaser configuration for Orbit
  .github/workflows/goreleaser-orbit.yaml
  orbit/.goreleaser.yml
Labels: #agent autoupdater

#3415 Update Orbit changelog for 0.0.4 release
  Makefile
  orbit/CHANGELOG.md
  orbit/changes/build-msi-root
  orbit/changes/extension-tables
  orbit/changes/flagfile-support
  orbit/changes/orbit-certs
  orbit/changes/uuid-identifier
Labels: #agent autoupdater

#3416 Remove certificate file after import in Orbit release Action
  .github/workflows/goreleaser-orbit.yaml
Labels: #agent autoupdater

#3458 Fix handling of enroll secret env vars in Orbit
  orbit/changes/fix-enroll-secret
  orbit/cmd/orbit/orbit.go
  orbit/pkg/update/hash.go
Labels: bug, #agent autoupdater, :golang dev

#3477 Don't strip debugging symbols from Orbit binary
  orbit/.goreleaser.yml
Labels: #agent autoupdater

#3478 Prepare for Orbit 0.0.5 release
  cmd/fleetctl/package.go
  orbit/CHANGELOG.md
  orbit/changes/fix-enroll-secret
Labels: :improve documentation

#3449 Hide warnings for removed migrations
  server/datastore/mysql/mysql.go
Labels: bug, :backend

#3360 Clean up E2E testing configurations
  .github/workflows/test.yml
  Makefile
  cypress.json
  cypress/cypress-free.json
  cypress/cypress-premium.json
  package.json
Labels: #contributor experience

#3530 Add Fleet server deployment in CI
  .github/workflows/build-binaries.yaml
  .github/workflows/deploy-staging.yml
  .vscode/launch.json
Labels: #contributor experience

#3531 Fix staging action to deploy Fleet server on PR and merge
  .github/workflows/build-binaries.yaml
  .github/workflows/deploy-staging.yml
Labels: #contributor experience

#3537 Add "Automations" documentation page
  docs/01-Using-Fleet/03-REST-API.md
  docs/01-Using-Fleet/13-Vulnerability-Processing.md
  docs/01-Using-Fleet/14-Automations.md
Labels: :improve documentation

#3538 Start staging tunnel in background
  .github/workflows/deploy-staging.yml
Labels: #contributor experience

#3540 Download artifact to build path in staging deploy
  .github/workflows/deploy-staging.yml
Labels: #contributor experience

#3539 Fix regex matching email in host search
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
Labels: bug, :golang dev

#3455 Add community section to Fleet Handbook
  handbook/README.md
  handbook/community.md
Labels: :improve documentation

#3542 Update Fleet handbook
  handbook/README.md
  handbook/engineering.md
  handbook/product.md
Labels: :improve handbook

#3544 Add no-hosts option to `fleetctl preview`
  cmd/fleetctl/preview.go
  handbook/product.md
Labels: #contributor experience, :golang dev
