Repository fleetdm/fleet, pull requests merged in 2021-02, with the labels that each got.

#251 Add --dev flag and change docker defaults
  cmd/fleet/main.go
  cmd/fleet/prepare.go
  cmd/fleet/serve.go
  docker-compose.yml
  docs/3-Contribution/1-Building-Fleet.md
Labels: development infrastructure

#259 Clean up development files
  Makefile
  tools/app/development.yml
  tools/app/kolide.yaml
  tools/minikube.yaml
Labels: development infrastructure

#263 Update Kolide to Fleet as appropriate in documentation
  cmd/fleetctl/login.go
  cmd/fleetctl/logout.go
  cmd/fleetctl/setup.go
  docs/2-Deployment/3-Adding-hosts.md
  server/service/client_setup.go
Labels: documentation

#266 Add debug flag to fleetctl
  cmd/fleetctl/api.go
  cmd/fleetctl/apply.go
  cmd/fleetctl/convert.go
  cmd/fleetctl/debug.go
  cmd/fleetctl/delete.go
  cmd/fleetctl/flags.go
  cmd/fleetctl/get.go
  cmd/fleetctl/goquery.go
  cmd/fleetctl/login.go
  cmd/fleetctl/logout.go
  cmd/fleetctl/preview.go
  cmd/fleetctl/query.go
  cmd/fleetctl/setup.go
  cmd/fleetctl/user.go
  server/service/client.go
Labels: enhancement

#272 Prepare for 3.7.1 release
  CHANGELOG.md
  tools/fleetctl-npm/package.json
Labels: documentation

#275 Update release instructions
  docs/3-Contribution/5-Releasing-Fleet.md
Labels: development infrastructure, documentation

#278 Add documentation for committing changes
  docs/3-Contribution/4-Architecture-decisions.md
  docs/3-Contribution/4-Commiting-Changes.md
  docs/3-Contribution/README.md
Labels: development infrastructure, documentation

#281 Update database migration tooling
  Makefile
  docs/3-Contribution/3-Migrations.md
  go.mod
  go.sum
  server/datastore/mysql/migrations/data/migration.go
  server/datastore/mysql/migrations/tables/migration.go
Labels: development infrastructure

#297 Deprecate /api/v1/kolide routes
  docs/1-Using-Fleet/3-REST-API.md
  docs/2-Deployment/2-Configuration.md
  frontend/kolide/endpoints.js
  frontend/kolide/entities/config.js
  frontend/kolide/entities/hosts.tests.js
  frontend/kolide/entities/packs.js
  frontend/kolide/websockets.js
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
  frontend/redux/nodes/entities/labels/actions.tests.js
  frontend/test/envSetup.js
  frontend/test/mocks/README.md
  frontend/test/mocks/config_mocks.js
  frontend/test/mocks/host_mocks.js
  frontend/test/mocks/invite_mocks.js
  frontend/test/mocks/label_mocks.js
  frontend/test/mocks/pack_mocks.js
  frontend/test/mocks/query_mocks.js
  frontend/test/mocks/scheduled_query_mocks.js
  frontend/test/mocks/session_mocks.js
  frontend/test/mocks/status_label_mocks.js
  frontend/test/mocks/target_mocks.js
  frontend/test/mocks/user_mocks.js
  frontend/test/target_mock.js
  server/service/client_appconfig.go
  server/service/client_carves.go
  server/service/client_hosts.go
  server/service/client_labels.go
  server/service/client_live_query.go
  server/service/client_options.go
  server/service/client_packs.go
  server/service/client_queries.go
  server/service/client_sessions.go
  server/service/client_targets.go
  server/service/client_users.go
  server/service/endpoint_appconfig_test.go
  server/service/endpoint_campaigns.go
  server/service/endpoint_test.go
  server/service/endpoint_users_test.go
  server/service/handler.go
  server/service/handler_test.go
  server/service/http_auth_test.go
  server/service/service_sessions.go
  server/service/transport_invites_test.go
  server/service/transport_labels_test.go
  server/service/transport_packs_test.go
  server/service/transport_queries_test.go
  server/service/transport_scheduled_queries_test.go
  server/service/transport_sessions_test.go
  server/service/transport_targets_test.go
  server/service/transport_users_test.go
  tools/api/kolide/me
  tools/api/kolide/packs/create
  tools/api/kolide/packs/list
  tools/api/kolide/packs/scheduled
  tools/api/kolide/queries/create
  tools/api/kolide/queries/list
  tools/api/kolide/schedule/add_query_to_pack
  tools/api/kolide/schedule/delete_scheduled_query
  tools/app/authtest.html
Labels: refactoring

#294 Add labels endpoint to REST API docs
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#301 Deprecate environment variable prefix
  .github/workflows/pr-helm.yaml
  chart/templates/deployment.yaml
  cmd/fleet/serve.go
  docs/2-Deployment/2-Configuration.md
  examples/kubernetes/fleet-deployment.yml
  examples/kubernetes/fleet-migrations.yml
  server/config/config.go
  tools/ci/k8s-templates/branch-deployment.template
  tools/ci/k8s-templates/pr-deployment.template
Labels: documentation, refactoring

#295 Fixes for fleetctl preview
  README.md
  cmd/fleetctl/config.go
  cmd/fleetctl/preview.go
Labels: bug, documentation

#328 Rename MySQL parameters for CircleCI
  .circleci/config.yml
  server/datastore/mysql_test.go
Labels: development infrastructure

#307 Add instructions for moving queries and packs from one Fleet env to another
  docs/1-Using-Fleet/2-fleetctl-CLI.md
Labels: documentation

#327 Add support for `query` parameter in list hosts endpoint
  server/datastore/datastore_hosts_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/kolide/hosts.go
  server/service/transport_hosts.go
Labels: enhancement

#331 Add /targets endpoint to REST API docs.
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#336 Remove github.com/golang/dep from Makefile
  Makefile
Labels: development infrastructure

#339 Return denylist parameter with pack configs
  server/kolide/osquery.go
  server/service/service_osquery.go
Labels: bug

#280 Edit /hosts endpoint in API docs
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#347 Add AWS Lambda as logging plugin
  .github/workflows/pr-helm.yaml
  chart/templates/deployment.yaml
  chart/values.yaml
  docs/1-Using-Fleet/4-Osquery-logs.md
  docs/2-Deployment/2-Configuration.md
  server/config/config.go
  server/logging/lambda.go
  server/logging/lambda_test.go
  server/logging/logging.go
  server/logging/mock/lambda.go
  server/test/testingt.go
Labels: enhancement

#352 Prepare for 3.8.0 release
  CHANGELOG.md
  chart/Chart.yaml
  tools/fleetctl-npm/package.json
Labels: documentation

#346 Add file carve endpoints and remaining user endpoints to REST API docs
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#359 Add comparison table to fleetdm.com
  website/assets/images/check-16x16@2x.png
  website/assets/images/ellipse-6x8@2x.png
  website/views/pages/homepage.ejs
Labels: website
