Repository fleetdm/fleet, pull requests merged in 2021-06, with the labels that each got.

#925 Specify that Fleet does not support Redis Sentinel in Configuration docs
  docs/3-Deployment/2-Configuration.md
Labels: :improve documentation

#927 Make create_figma script executable
  tools/api/fleet/teams/create_figma
Labels: #contributor experience

#942 Fix checkbox styles on master branch
  frontend/components/forms/InviteUserForm/_styles.scss
  frontend/components/forms/fields/Checkbox/Checkbox.jsx
  frontend/components/forms/fields/Checkbox/_styles.scss
Labels: :frontend dev (Fleet UI)

#943 Remove Redis read/write timeouts
  server/pubsub/redis_query_results.go
Labels: bug

#945 Query library improvements
  website/assets/images/chevron-down-9x6@2x.png
  website/assets/images/icon-search-16x16@2x.png
  website/assets/js/pages/query-detail.page.js
  website/assets/js/pages/query-library.page.js
  website/assets/styles/pages/query-detail.less
  website/assets/styles/pages/query-library.less
  website/views/pages/query-detail.ejs
  website/views/pages/query-library.ejs
Labels: #website

#950 Return error messages for authentication errors
  server/service/middleware/authzcheck/authzcheck.go
  server/service/middleware/authzcheck/authzcheck_test.go
Labels: #teams/RBAC

#949 Filter hosts and label counts by teams
  server/datastore/datastore_hosts.go
  server/datastore/datastore_labels.go
  server/datastore/inmem/hosts.go
  server/datastore/inmem/labels.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/labels.go
  server/kolide/hosts.go
  server/kolide/labels.go
  server/mock/datastore_hosts.go
  server/mock/datastore_labels.go
  server/service/service_campaigns.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
  server/service/service_labels.go
Labels: #teams/RBAC

#954 Remove deprecated config options
  cmd/fleet/serve.go
Labels: not backwards compatible

#955 Fix tls_compatibility key in yaml config
  docs/3-Deployment/2-Configuration.md
  server/config/config.go
  server/config/config_test.go
Labels: not backwards compatible

#960 Update action button styles on "Manage packs" page and "Manage queries" page
  frontend/pages/packs/AllPacksPage/AllPacksPage.jsx
  frontend/pages/packs/AllPacksPage/AllPacksPage.tests.jsx
  frontend/pages/packs/AllPacksPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.jsx
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.tests.jsx
  frontend/pages/queries/ManageQueriesPage/_styles.scss
Labels: #spiffier, #teams/RBAC, :frontend dev (Fleet UI)

#957 Remove deprecated kolide names from API routes and configuration
  docs/1-Using-Fleet/3-REST-API.md
  docs/3-Deployment/2-Configuration.md
  server/config/config.go
  server/service/handler.go
  server/service/handler_test.go
  server/service/http_auth_test.go
Labels: not backwards compatible

#972 Log subject/object/action with authz failures
  server/authz/authz.go
  server/authz/errors.go
  server/kolide/errors.go
  server/service/handler.go
  server/service/middleware/authzcheck/authzcheck.go
Labels: :improve error message

#979 Remove JWT in Fleet session management
  Makefile
  charts/fleet/README.md
  charts/fleet/templates/deployment.yaml
  charts/fleet/values.yaml
  cmd/fleet/main.go
  cmd/fleet/serve.go
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-deployment.yml
  docs/3-Deployment/2-Configuration.md
  docs/3-Deployment/4-Example-deployment-scenarios.md
  server/config/config.go
  server/fleet/sessions.go
  server/service/debug_handler.go
  server/service/debug_handler_test.go
  server/service/endpoint_campaigns.go
  server/service/endpoint_middleware.go
  server/service/endpoint_test.go
  server/service/handler.go
  server/service/handler_test.go
  server/service/http_auth.go
  server/service/http_auth_test.go
  server/service/service_sessions.go
  server/service/service_sessions_test.go
  tools/ci/helm-values/custom-annotations.yaml
  tools/ci/helm-values/disable-fleet-tls.yaml
  tools/ci/helm-values/enable-cloudsql-proxy.yaml
  tools/ci/helm-values/enable-mysql-tls.yaml
  tools/ci/helm-values/logger-firehose-accesssid.yaml
  tools/ci/helm-values/logger-firehose-sts.yaml
  tools/ci/helm-values/logger-pubsub.yaml
  tools/ci/k8s-templates/branch-deployment.template
  tools/ci/k8s-templates/pr-deployment.template
Labels: :refactor

#980 Change name of localstorage auth token
  cypress/support/commands.ts
  frontend/components/queries/QueryPageWrapper/QueryPageWrapper.tests.jsx
  frontend/components/queries/QueryPageWrapper/helpers.tests.js
  frontend/utilities/local.js
  server/service/endpoint_sessions.go
  tools/app/authtest.html
Labels: :refactor

#982 Rename frontend icon component
  assets/fonts/fleeticons/fleeticons.woff
  assets/fonts/fleeticons/fleeticons.woff2
  frontend/components/Pagination/Pagination.jsx
  frontend/components/Pagination/_style.scss
  frontend/components/StackedWhiteBoxes/StackedWhiteBoxes.jsx
  frontend/components/TableContainer/_styles.scss
  frontend/components/config/EnrollSecretTable/EnrollSecretTable.jsx
  frontend/components/flash_messages/FlashMessage/FlashMessage.jsx
  frontend/components/flash_messages/FlashMessage/_styles.scss
  frontend/components/flash_messages/PersistentFlash/PersistentFlash.jsx
  frontend/components/forms/ConfigurePackQueryForm/_styles.scss
  frontend/components/forms/fields/InputFieldWithIcon/InputFieldWithIcon.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetDetails/TargetDetails.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetDetails/TargetDetails.tests.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetOption/TargetIcon.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetOption/TargetOption.tests.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/_styles.scss
  frontend/components/icons/FleetIcon/FleetIcon.jsx
  frontend/components/icons/FleetIcon/FleetIcon.tests.jsx
  frontend/components/icons/FleetIcon/index.js
  frontend/components/icons/KolideIcon/KolideIcon.tests.jsx
  frontend/components/icons/KolideIcon/index.js
  frontend/components/icons/PlatformIcon/PlatformIcon.jsx
  frontend/components/icons/PlatformIcon/PlatformIcon.tests.jsx
  frontend/components/packs/EditPackFormWrapper/_styles.scss
  frontend/components/queries/QueryResultsTable/QueryResultsTable.jsx
  frontend/components/queries/QueryResultsTable/_styles.scss
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesList.jsx
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.jsx
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.tests.jsx
  frontend/components/queries/ScheduledQueriesList/_styles.scss
  frontend/components/side_panels/QueryDetailsSidePanel/_styles.scss
  frontend/components/side_panels/QuerySidePanel/QuerySidePanel.jsx
  frontend/components/side_panels/QuerySidePanel/_styles.scss
  frontend/components/side_panels/ScheduleQuerySidePanel/SearchPackQuery/SearchPackQuery.jsx
  frontend/pages/RegistrationPage/Breadcrumbs/_styles.scss
  frontend/pages/UserSettingsPage/UserSettingsPage.jsx
  frontend/pages/UserSettingsPage/_styles.scss
  frontend/pages/admin/AppSettingsPage/_styles.scss
  frontend/pages/hosts/HostDetailsPage/SelectQueryModal/_styles.scss
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/pages/hosts/ManageHostsPage/components/AddHostModal/AddHostModal.jsx
  frontend/pages/hosts/ManageHostsPage/components/AddHostModal/_styles.scss
  frontend/styles/global/_fonts.scss
  frontend/styles/global/_icons.scss
Labels: :refactor

#985 Explicitly set base branch for markdown link check
  .github/workflows/docs.yml
Labels: #contributor experience

#983 Rename custom ACE editor
  frontend/components/FleetAce/FleetAce.jsx
  frontend/components/FleetAce/_styles.scss
  frontend/components/FleetAce/index.js
  frontend/components/FleetAce/mode.js
  frontend/components/FleetAce/theme.css
  frontend/components/FleetAce/theme.js
  frontend/components/KolideAce/index.js
  frontend/components/KolideAce/theme.css
  frontend/components/YamlAce/YamlAce.jsx
  frontend/components/YamlAce/_styles.scss
  frontend/components/forms/LabelForm/LabelForm.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetDetails/TargetDetails.jsx
  frontend/components/forms/queries/QueryForm/QueryForm.jsx
  frontend/components/side_panels/QueryDetailsSidePanel/QueryDetailsSidePanel.jsx
  frontend/components/side_panels/QueryDetailsSidePanel/QueryDetailsSidePanel.tests.jsx
  frontend/components/side_panels/QueryDetailsSidePanel/_styles.scss
  frontend/components/side_panels/ScheduleQuerySidePanel/SearchPackQuery/SearchPackQuery.jsx
  frontend/components/side_panels/ScheduleQuerySidePanel/SearchPackQuery/_styles.scss
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/pages/queries/QueryPage/QueryPage.jsx
  frontend/pages/queries/QueryPage/_styles.scss
Labels: :refactor

#995 Update fleetctl user create for Teams
  cmd/fleetctl/user.go
Labels: #teams/RBAC

#996 Fix up test osquery tooling
  docs/4-Contribution/2-Testing.md
  tools/osquery/README.md
  tools/osquery/docker-compose.yml
  tools/osquery/example_osquery.flags
Labels: :improve documentation

#998 Add "Fleet tier" and "User role" as fields in "Bug" issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/docs.yml
Labels: #contributor experience

#997 Add link to simulated host instructions in Testing docs
  docs/4-Contribution/2-Testing.md
Labels: #teams/RBAC, :improve documentation

#894 Add support process to /handbook
  handbook/support-process.md
Labels: :improve documentation

#1020 Replace "24 hours" with "1 business day" in handbook/support-process
  handbook/support-process.md
Labels: :improve documentation

#1005 Set up Cypress testing for Teams/Tiers
  Makefile
  cypress/integration/all/app/manageUsers.spec.ts
  cypress/integration/all/app/settingsflow.spec.ts
  cypress/integration/all/sessions/sessions.spec.ts
  cypress/integration/all/sessions/sso.spec.ts
  cypress/integration/basic/admin.spec.ts
  cypress/integration/basic/maintainer.spec.ts
  cypress/integration/basic/observer.spec.ts
  cypress/integration/basic/team_maintainer_observer.spec.ts
  cypress/integration/core/README.md
  cypress/integration/core/admin.spec.ts
  cypress/integration/core/maintainer.spec.ts
  cypress/integration/core/observer.spec.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  docker-compose.yml
  tools/api/fleet/teams/create_core
  tools/saml/README.md
  tools/saml/users.php
Labels: #contributor experience, #teams/RBAC

#1033 Allow team user to view host details page
  server/service/service_hosts.go
Labels: #teams/RBAC, bug

#1029 Create/edit user modal: Fleet Core UI
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/admin/UserManagementPage/components/EditUserModal/EditUserModal.tsx
  frontend/pages/admin/UserManagementPage/components/UserForm/UserForm.tsx
Labels: #teams/RBAC, :frontend dev (Fleet UI), bug

#1027 Host details page: Remove Query and Delete button for observers only
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
Labels: #teams/RBAC, :frontend dev (Fleet UI), bug

#383 Additions and changes to Fleet REST API for multiple teams
  docs/1-Using-Fleet/3-REST-API.md
Labels: #teams/RBAC, :improve documentation

#472 Documentation for RBAC and teams
  docs/1-Using-Fleet/8-Permissions.md
  docs/1-Using-Fleet/9-Teams.md
Labels: #teams/RBAC, :improve documentation

#1036 Change user settings dropdown for current user
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/admin/UserManagementPage/UsersTableConfig.tsx
  frontend/pages/admin/UserManagementPage/_styles.scss
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1042 Appropriately filter teams returned in targets API
  server/datastore/mysql/teams.go
Labels: #teams/RBAC, bug

#1043 Fix targeting Teams in live queries
  server/datastore/mysql/campaigns.go
  server/service/service_campaigns.go
Labels: #teams/RBAC, bug

#1049 User Management Page: Fix bug allowing to delete active user
  frontend/redux/nodes/entities/users/config.js
Labels: :frontend dev (Fleet UI), bug

#1040 Query Edit/Run Page: Conditionally render Teams grouping in select targets dropdown
  frontend/components/forms/fields/SelectTargetsDropdown/SelectTargetsDropdown.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/SelectTargetsMenu/SelectTargetsMenu.jsx
  frontend/components/queries/QueryPageSelectTargets/QueryPageSelectTargets.jsx
  frontend/pages/queries/QueryPage/QueryPage.jsx
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
Labels: #teams/RBAC, :frontend dev (Fleet UI), bug

#1037 Fix for cannot run query for selected teams
  frontend/components/forms/fields/SelectTargetsDropdown/SelectTargetsDropdown.tests.jsx
  frontend/fleet/entities/packs.tests.js
  frontend/fleet/helpers.tests.js
  frontend/fleet/helpers.ts
  frontend/test/target_mock.js
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1051 Update CHANGELOG and bump versioning for prerelease
  CHANGELOG.md
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/fleetctl-npm/package.json
Labels: #teams/RBAC

#1050 Add support for license key in fleetctl preview
  cmd/fleetctl/preview.go
Labels: #teams/RBAC

#1048 Fix styling of action dropdown button
  frontend/pages/admin/TeamManagementPage/_styles.scss
Labels: #teams/RBAC, :frontend dev (Fleet UI), bug

#973 Query library improvements -- Round 2
  docs/1-Using-Fleet/standard-query-library/standard-query-library.yml
  website/assets/images/icon-search-16x16@2x.png
  website/assets/js/pages/query-detail.page.js
  website/assets/js/pages/query-library.page.js
  website/assets/styles/bootstrap-overrides.less
  website/assets/styles/layout.less
  website/assets/styles/pages/query-detail.less
  website/assets/styles/pages/query-library.less
  website/scripts/build-static-content.js
  website/views/pages/query-detail.ejs
  website/views/pages/query-library.ejs
Labels: #query library, #website

#1059 Rename components and errors in setup flow
  frontend/components/forms/RegistrationForm/ConfirmationPage/ConfirmationPage.jsx
  frontend/components/forms/RegistrationForm/FleetDetails/FleetDetails.jsx
  frontend/components/forms/RegistrationForm/FleetDetails/FleetDetails.tests.jsx
  frontend/components/forms/RegistrationForm/FleetDetails/helpers.js
  frontend/components/forms/RegistrationForm/FleetDetails/index.js
  frontend/components/forms/RegistrationForm/KolideDetails/helpers.js
  frontend/components/forms/RegistrationForm/KolideDetails/index.js
  frontend/components/forms/RegistrationForm/RegistrationForm.jsx
  frontend/components/forms/RegistrationForm/RegistrationForm.tests.jsx
  frontend/interfaces/registration_form_data.js
Labels: :refactor

#1060 Update release documentation
  docs/4-Contribution/5-Releasing-Fleet.md
Labels: #contributor experience

#1076 Add question and answer for missing column error in Using Fleet FAQ
  docs/1-Using-Fleet/FAQ.md
Labels: :improve documentation

#1073 Fix set up flow styles
  frontend/components/forms/RegistrationForm/_styles.scss
Labels: #spiffier, #teams/RBAC, :frontend dev (Fleet UI)

#1083 Make password criteria messaging consistent
  frontend/components/forms/ChangePasswordForm/ChangePasswordForm.jsx
  frontend/components/forms/ChangePasswordForm/ChangePasswordForm.tests.jsx
  frontend/components/forms/ChangePasswordForm/validate.js
  frontend/components/forms/RegistrationForm/AdminDetails/AdminDetails.tests.jsx
  frontend/components/forms/RegistrationForm/AdminDetails/helpers.js
  frontend/components/forms/ResetPasswordForm/ResetPasswordForm.jsx
  frontend/components/forms/ResetPasswordForm/ResetPasswordForm.tests.jsx
  frontend/components/forms/ResetPasswordForm/validate.js
Labels: #spiffier, #teams/RBAC, :frontend dev (Fleet UI)

#1090 Add hosts count to Team details page
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/TeamDetailsWrapper.tsx
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/_styles.scss
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1089 Add commands for enrolling hosts in E2E tests
  Makefile
  cypress/integration/all/app/hosts.spec.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  package.json
  tools/osquery/docker-compose.yml
  yarn.lock
Labels: #contributor experience

#1082 Cypress e2e test for teams global admin (Fleet basic tier)
  cypress/integration/basic/admin.spec.ts
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1093 Handle missing server_url in setup
  server/service/endpoint_setup.go
  server/service/validation_setup.go
Labels: bug

#1086 Update links to main branch in email templates
  server/mail/templates/change_email_confirmation.html
  server/mail/templates/invite_token.html
  server/mail/templates/password_reset.html
  server/mail/templates/smtp_setup.html
  server/service/service.go
Labels: #spiffier

#1091 Add tips for asking follow up questions in support process documentation
  .github/workflows/markdown-link-check-config.json
  handbook/support-process.md
Labels: :improve documentation

#1094 Cypress e2e test for global admin (Fleet core tier)
  cypress/integration/core/admin.spec.ts
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1104 Add "Queries" to nav
  website/views/layouts/layout.ejs
Labels: #website

#1097 Clean up service and return license errors
  frontend/pages/LoginPage/LoginPage.jsx
  server/authz/errors.go
  server/contexts/viewer/viewer.go
  server/fleet/errors.go
  server/service/endpoint_appconfig.go
  server/service/endpoint_middleware.go
  server/service/endpoint_middleware_test.go
  server/service/handler.go
  server/service/middleware/authzcheck/authzcheck.go
  server/service/service_campaigns.go
  server/service/service_teams.go
  server/service/transport_error.go
  server/service/validation_users.go
Labels: #teams/RBAC, :refactor

#1112 E2e testing: Add stopDockerHost command to Cypress tests
  cypress/integration/basic/admin.spec.ts
  cypress/integration/basic/team_maintainer_observer.spec.ts
  cypress/integration/core/admin.spec.ts
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1113 Fix loading of enroll secrets for Teams
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: #teams/RBAC, bug

#1114 Reorder migrations for pre-4.0 upgrades
  server/datastore/mysql/migrations/tables/20210601000001_CreateTeamsTables.go
  server/datastore/mysql/migrations/tables/20210601000002_AddRolesToInvites.go
  server/datastore/mysql/migrations/tables/20210601000003_MigrateAdmin.go
  server/datastore/mysql/migrations/tables/20210601000004_DeleteUsers.go
  server/datastore/mysql/migrations/tables/20210601000005_TeamsAgentOptions.go
  server/datastore/mysql/migrations/tables/20210601000006_TeamsGlobalAgentOptions.go
  server/datastore/mysql/migrations/tables/20210601000007_TeamsObserverQueries.go
  server/datastore/mysql/migrations/tables/20210601000008_TeamsEnrollSecrets.go
Labels: :golang dev, :refactor, bug

#1119 Add backend and fleetctl support for API-only user
  cmd/fleetctl/user.go
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/mysql/migrations/tables/20210616163757_AddApiOnlyToUser.go
  server/datastore/mysql/users.go
  server/fleet/users.go
Labels: :golang dev

#1122 Move "connecting to the Mailhog simulated server" out of the FAQ
  docs/4-Contribution/2-Testing.md
  docs/4-Contribution/FAQ.md
Labels: :improve documentation

#1131 Add persistence to saved columns in "Hosts" table after user logs out
  frontend/redux/middlewares/auth.js
  frontend/utilities/local.js
Labels: :frontend dev (Fleet UI)

#1137 Return license info after app config modified
  server/service/endpoint_appconfig.go
Labels: #teams/RBAC, bug

#1130 Allow Packs to be targeted to Teams
  frontend/components/forms/packs/EditPackForm/EditPackForm.jsx
  frontend/components/forms/packs/PackForm/PackForm.jsx
  frontend/components/packs/EditPackFormWrapper/EditPackFormWrapper.jsx
  frontend/fleet/entities/teams.ts
  frontend/fleet/helpers.ts
  frontend/pages/packs/EditPackPage/EditPackPage.jsx
  frontend/pages/packs/EditPackPage/EditPackPage.tests.jsx
  frontend/pages/packs/PackComposerPage/PackComposerPage.jsx
  frontend/pages/packs/PackComposerPage/PackComposerPage.tests.jsx
  frontend/redux/nodes/entities/packs/config.js
  frontend/redux/nodes/entities/scheduled_queries/config.js
  frontend/redux/nodes/entities/teams/config.ts
  frontend/test/stubs.ts
  server/datastore/datastore.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_packs.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/migrations/tables/20210617174723_PackTargetForeignKey.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/packs.go
  server/datastore/mysql/queries.go
  server/datastore/mysql/scheduled_queries.go
  server/fleet/packs.go
  server/fleet/targets.go
  server/service/endpoint_appconfig.go
  server/service/endpoint_packs.go
  server/service/logging_packs.go
  server/service/service_labels.go
  server/service/service_osquery.go
  server/service/service_packs.go
  server/test/comparisons.go
Labels: #teams/RBAC, :frontend dev (Fleet UI), :golang dev

#1132 Input field and form field error state
  frontend/components/forms/ConfigurePackQueryForm/ConfigurePackQueryForm.jsx
  frontend/components/forms/ConfigurePackQueryForm/validate.js
  frontend/components/forms/FormField/_styles.scss
  frontend/components/forms/fields/Dropdown/_styles.scss
  frontend/components/forms/fields/InputField/_styles.scss
  frontend/components/forms/fields/InputFieldWithIcon/_styles.scss
Labels: #spiffier, :frontend dev (Fleet UI)

#1139 Properly append to env in preview command execs
  cmd/fleetctl/preview.go
Labels: #fleetctl

#1143 Restructure documentation in preparation for docs living on fleetdm.com
  .github/ISSUE_TEMPLATE/bug-report.md
  CHANGELOG.md
  docs/1-Using-Fleet/1-Fleet-UI.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/4-Adding-hosts.md
  docs/1-Using-Fleet/5-Osquery-logs.md
  docs/1-Using-Fleet/6-Monitoring-Fleet.md
  docs/1-Using-Fleet/7-Security-best-practices.md
  docs/1-Using-Fleet/8-Updating-Fleet.md
  docs/1-Using-Fleet/FAQ.md
  docs/1-Using-Fleet/README.md
  docs/1-Using-Fleet/standard-query-library/README.md
  docs/2-Deploying/1-Installation.md
  docs/2-Deploying/2-Configuration.md
  docs/2-Deploying/3-Example-deployment-scenarios.md
  docs/2-Deploying/4-fleetctl-agent-updates.md
  docs/2-Deploying/FAQ.md
  docs/2-Deploying/README.md
  docs/2-Orbit-osquery/README.md
  docs/3-Contributing/1-Building-Fleet.md
  docs/3-Contributing/2-Testing.md
  docs/3-Contributing/3-Migrations.md
  docs/3-Contributing/4-Committing-Changes.md
  docs/3-Contributing/5-Releasing-Fleet.md
  docs/3-Contributing/FAQ.md
  docs/3-Contributing/README.md
  docs/README.md
  frontend/README.md
  frontend/components/hosts/AddHostModal/AddHostModal.jsx
  handbook/manual-qa.md
  handbook/release-process.md
  tools/backup_db/README.md
  website/config/routes.js
Labels: #website, :improve documentation

#1151 Update links to documentation so that they use main branch
  .github/ISSUE_TEMPLATE/bug-report.md
  CHANGELOG.md
  README.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/7-Security-best-practices.md
  docs/3-Contributing/5-Releasing-Fleet.md
  frontend/README.md
  frontend/components/hosts/AddHostModal/AddHostModal.jsx
  frontend/components/side_panels/UserMenu/UserMenu.jsx
  frontend/pages/admin/OsqueryOptionsPage/OsqueryOptionsPage.jsx
  handbook/release-process.md
  tools/fleetctl-npm/README.md
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/get-started.ejs
Labels: #website, :improve documentation

#1157 Add license section to configuration documentation
  docs/2-Deploying/2-Configuration.md
Labels: :improve documentation

#1156 Sort labels for membership update
  server/datastore/mysql/labels.go
Labels: :golang dev, :refactor

#1155 Display default for empty name and author fields
  frontend/components/queries/QueriesList/QueriesListRow/QueriesListRow.jsx
  frontend/pages/admin/UserManagementPage/UsersTableConfig.tsx
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1161 Update development documentation for SSO testing
  docs/3-Deployment/2-Configuration.md
  docs/4-Contribution/2-Testing.md
Labels: #contributor experience

#1164 Add label ID to get labels response
  server/datastore/datastore_labels.go
  server/datastore/mysql/labels.go
  server/fleet/labels.go
Labels: bug

#1167 Backend and fleetctl for usage analytics
  cmd/fleetctl/setup.go
  go.sum
  server/datastore/mysql/app_configs.go
  server/datastore/mysql/migrations/tables/20210622160235_AddAnalyticsToAppConfig.go
  server/fleet/app.go
  server/service/endpoint_appconfig.go
  server/service/service_appconfig.go
Labels: #fleet-server-config, :golang dev

#1165 Add documentation on new --dev_license flag
  docs/4-Contribution/2-Testing.md
Labels: #contributor experience

#1171 Fix forbidden error for password reset
  server/service/service_users.go
Labels: #teams/RBAC, bug

#1182 Fix authorization check in reset password
  server/service/service_users.go
Labels: #teams/RBAC, bug

#1183 Make naming of host columns consistent
  cmd/fleetctl/goquery.go
  cmd/fleetctl/query_output.go
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/datastore_hosts.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_targets.go
  server/datastore/datastore_unicode.go
  server/datastore/inmem/hosts.go
  server/datastore/inmem/inmem.go
  server/datastore/inmem/invites.go
  server/datastore/inmem/packs.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/migrations/tables/20210623133615_ConsistentColumnNames.go
  server/fleet/hosts.go
  server/pubsub/query_results_test.go
  server/service/endpoint_hosts.go
  server/service/endpoint_middleware_test.go
  server/service/endpoint_targets.go
  server/service/service_campaigns.go
  server/service/service_carves.go
  server/service/service_hosts_test.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/service/service_targets_test.go
  server/service/transport.go
  server/test/new_objects.go
Labels: :golang dev, :refactor, not backwards compatible

#1184 Use global options as default for new teams
  ee/server/service/service_teams.go
Labels: #teams/RBAC, :golang dev

#1179 Revise help text on team members page
  cypress/integration/basic/admin.spec.ts
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1187 Fix additional permission error in reset password
  server/service/service_users.go
Labels: #teams/RBAC, :golang dev, bug

#1190 Add documentation for setting global and team agent options in Fleet UI
  docs/1-Using-Fleet/1-Fleet-UI.md
  docs/images/global-agent-options.png
  docs/images/team-agent-options.png
Labels: :improve documentation

#1197 Update support process documentation
  handbook/support-process.md
Labels: :improve documentation

#1196 Add usage statistics documentation to Using-Fleet section
  docs/1-Using-Fleet/10-Usage-statistics.md
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.jsx
Labels: :improve documentation

#1195 Add information about use of differential queries in Lambda documentation
  docs/1-Using-Fleet/5-Osquery-logs.md
Labels: :improve documentation

#1204 Update notification message for inviting users and update notification styles
  frontend/components/flash_messages/FlashMessage/FlashMessage.jsx
  frontend/components/flash_messages/FlashMessage/_styles.scss
  frontend/pages/admin/AppSettingsPage/AppSettingsPage.jsx
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/AgentOptionsPage/AgentOptionsPage.tsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/packs/EditPackPage/EditPackPage.jsx
  frontend/pages/queries/QueryPage/QueryPage.jsx
Labels: #spiffier, :frontend dev (Fleet UI)

#1205 Add success notification for creating and updating labels
  cypress/integration/all/app/labelflow.spec.ts
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: #spiffier, :frontend dev (Fleet UI)

#1202 Fix invite email template
  server/mail/templates/invite_token.html
Labels: #fleet-server-config, bug

#1207 Add sentence casing to "Full name" fields and remove letter spacing from "Password" fields
  frontend/components/forms/ConfirmInviteForm/ConfirmInviteForm.jsx
  frontend/components/forms/ConfirmSSOInviteForm/ConfirmSSOInviteForm.jsx
  frontend/components/forms/UserSettingsForm/UserSettingsForm.jsx
  frontend/components/forms/fields/InputField/_styles.scss
  frontend/components/forms/fields/InputFieldWithIcon/_styles.scss
  frontend/pages/admin/UserManagementPage/components/UserForm/UserForm.tsx
Labels: #spiffier

#1213 Add testing `fleetctl` to the manual QA doc and update example config files
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/agent-options.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/enroll-secrets.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/organization-settings.yml
  docs/1-Using-Fleet/configuration-files/multi-file-configuration/pack.yml
  handbook/manual-qa.md
Labels: #teams/RBAC, :improve documentation

#1214 In support process docs, add instruction on adding milestones to feature request issues
  handbook/support-process.md
Labels: :improve documentation

#1215 Implement release automation
  .github/workflows/goreleaser.yaml
  .goreleaser.yml
  docs/4-Contribution/5-Releasing-Fleet.md
  go.mod
  go.sum
  tools/docker/fleet.Dockerfile
  tools/docker/fleetctl.Dockerfile
  tools/fleetctl-npm/run.js
Labels: #contributor experience

#1217 Fix doc directories
  docs/3-Deployment/1-Installation.md
  docs/3-Deployment/2-Configuration.md
  docs/3-Deployment/3-Example-deployment-scenarios.md
  docs/3-Deployment/4-fleetctl-agent-updates.md
  docs/3-Deployment/FAQ.md
  docs/3-Deployment/README.md
  docs/4-Contribution/1-Building-Fleet.md
  docs/4-Contribution/2-Testing.md
  docs/4-Contribution/3-Migrations.md
  docs/4-Contribution/4-Committing-Changes.md
  docs/4-Contribution/5-Releasing-Fleet.md
  docs/4-Contribution/FAQ.md
  docs/4-Contribution/README.md
Labels: :improve documentation

#1218 Fix URLs in documentation
  cypress/README.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/7-Security-best-practices.md
  docs/1-Using-Fleet/FAQ.md
  docs/2-Orbit-osquery/README.md
  handbook/manual-qa.md
Labels: :improve documentation

#1230 Update documentation structure
  CHANGELOG.md
  cypress/README.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/7-Security-best-practices.md
  docs/1-Using-Fleet/9-Teams.md
  docs/1-Using-Fleet/FAQ.md
  docs/2-Deploying/1-Installation.md
  docs/2-Deploying/2-Configuration.md
  docs/2-Deploying/3-Example-deployment-scenarios.md
  docs/2-Deploying/4-fleetctl-agent-updates.md
  docs/2-Deploying/FAQ.md
  docs/2-Deploying/README.md
  docs/2-Orbit-osquery/README.md
  docs/3-Contributing/1-Building-Fleet.md
  docs/3-Contributing/2-Testing.md
  docs/3-Contributing/3-Migrations.md
  docs/3-Contributing/4-Committing-Changes.md
  docs/3-Contributing/5-Releasing-Fleet.md
  docs/3-Contributing/FAQ.md
  docs/3-Contributing/README.md
  frontend/README.md
  handbook/manual-qa.md
Labels: :improve documentation

#1211 Add ability to rotate a user's API token
  cypress/integration/all/app/resetsessions.spec.ts
  frontend/fleet/endpoints.ts
  frontend/fleet/entities/users.js
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/admin/UserManagementPage/UsersTableConfig.tsx
  frontend/pages/admin/UserManagementPage/components/ResetSessionsModal/ResetSessionsModal.tsx
  frontend/pages/admin/UserManagementPage/components/ResetSessionsModal/_styles.scss
  frontend/pages/admin/UserManagementPage/components/ResetSessionsModal/index.ts
  frontend/redux/nodes/entities/users/actions.js
Labels: :frontend dev (Fleet UI)

#1236 Add documentation for publishing a prerelease version of fleetctl to npm
  docs/3-Contributing/5-Releasing-Fleet.md
Labels: :improve documentation

#1221 Display "No team" in Hosts table if the host is not assigned to any team
  frontend/fleet/helpers.ts
  frontend/pages/hosts/ManageHostsPage/HostTableConfig.tsx
Labels: #teams/RBAC, :frontend dev (Fleet UI)

#1220 Host Details Page: Render vulnerable software warnings
  assets/images/icon-issue-fleet-black-50-16x16@2x.png
  frontend/components/IconToolTip/IconToolTip.tsx
  frontend/interfaces/software.ts
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareListRow/SoftwareListRow.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareVulnerabilities/SoftwareVulnerabilities.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareVulnerabilities/_styles.scss
  frontend/pages/hosts/HostDetailsPage/SoftwareVulnerabilities/index.js
  frontend/pages/hosts/HostDetailsPage/_styles.scss
Labels: :frontend dev (Fleet UI)

#1235 Update REST API documentation in preparation for Fleet 4.0.0
  docs/1-Using-Fleet/3-REST-API.md
Labels: #teams/RBAC, :improve documentation

#1243 Allow global maintainer to transfer hosts between Teams
  server/service/service_hosts.go
Labels: #teams/RBAC, :golang dev, bug

#1240 Redirect user to login when they reset their own sessions/API tokens from admin user management page
  cypress/integration/all/app/resetsessions.spec.ts
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
Labels: :frontend dev (Fleet UI)

#1251 Fix frontend rendering error when software vulnerabilities missing
  Makefile
  frontend/pages/hosts/HostDetailsPage/SoftwareListRow/SoftwareListRow.jsx
Labels: :frontend dev (Fleet UI), bug

#1254 Add logging for Teams endpoints
  server/service/logging_teams.go
Labels: :golang dev

#1244 Improvements to fleetctl enroll secret specs
  cypress/support/commands.ts
  frontend/redux/nodes/app/actions.js
  server/fleet/app.go
  server/service/endpoint_appconfig.go
Labels: :golang dev, not backwards compatible

#1253 Move configuration examples out of fleetctl-CLI documentation
  docs/1-Using-Fleet/10-Teams.md
  docs/1-Using-Fleet/11-Usage-statistics.md
  docs/1-Using-Fleet/12-Supported-browsers.md
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/9-Permissions.md
  docs/1-Using-Fleet/configuration-files/README.md
Labels: :improve documentation

#1256 Update /hosts/actions to use one file instead of two (redux)
  frontend/redux/nodes/entities/hosts/actions.js
  frontend/redux/nodes/entities/hosts/actions.ts
Labels: :frontend dev (Fleet UI)

#1267 Include Team names when listing label hosts
  server/datastore/mysql/labels.go
Labels: #teams/RBAC, :golang dev, bug
