Repository fleetdm/fleet, pull requests merged in 2021-07, with the labels that each got.

#1280 Fix migration for MariaDB compatibility
  docker-compose.yml
  server/datastore/mysql/migrations/tables/20210601000001_CreateTeamsTables.go
  server/datastore/mysql/migrations/tables/20210601000008_TeamsEnrollSecrets.go
Labels: :golang dev, bug

#1291 Adjust column headers on pricing page
  website/views/pages/pricing.ejs
Labels: #website

#1285 Update create user validation and documentation
  docs/1-Using-Fleet/3-REST-API.md
  server/fleet/users.go
  server/service/service_users.go
  server/service/validation_users.go
Labels: :golang dev, :improve documentation

#1299 Update table row height and button font size
  frontend/components/TableContainer/DataTable/_styles.scss
  frontend/components/buttons/Button/_styles.scss
  frontend/components/queries/QueriesList/QueriesListRow/_styles.scss
  frontend/pages/hosts/HostDetailsPage/PackQueriesListRow/_styles.scss
Labels: #spiffier

#1304 Add link to Loom video that walks through setting up dev environment
  docs/3-Contributing/1-Building-Fleet.md
Labels: :improve documentation

#1307 Add FAQ entries for common migration and TLS questions
  docs/2-Deploying/FAQ.md
Labels: :improve documentation

#1310 Update examples in documentation to use FleetDM where possible
  docs/1-Using-Fleet/2-fleetctl-CLI.md
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/4-Adding-hosts.md
  docs/1-Using-Fleet/configuration-files/README.md
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-deployment.yml
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-migrations.yml
  docs/1-Using-Fleet/configuration-files/kubernetes/fleet-service.yml
  docs/2-Deploying/3-Example-deployment-scenarios.md
  docs/2-Deploying/FAQ.md
Labels: :improve documentation

#1312 Allow Redis connection with unknown CLUSTER command
  changes/1312-gcp-redis
  server/pubsub/redis_query_results.go
Labels: :golang dev, bug

#1328 Add note about usernames and SSO to changelog
  CHANGELOG.md
Labels: :improve documentation

#1297 Fleetdm.com: Template for documentation pages
  website/api/controllers/view-docs-template.js
  website/api/controllers/view-documentation.js
  website/assets/images/chevron-right-6x9@2x.png
  website/assets/images/fleet-support-140x72@2x.png
  website/assets/images/install-fleet-140x72@2x.png
  website/assets/js/pages/docs-template.page.js
  website/assets/js/pages/documentation.page.js
  website/assets/styles/importer.less
  website/assets/styles/mixins-and-variables/colors.less
  website/assets/styles/pages/docs-template.less
  website/assets/styles/pages/documentation.less
  website/assets/styles/pages/homepage.less
  website/config/env/development.js
  website/config/policies.js
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/docs-template.ejs
  website/views/pages/documentation.ejs
Labels: #website

#1341 Fleetdm.com: Adjust header and footer padding
  website/views/layouts/layout.ejs
Labels: #website

#1353 Update documentation for auto table construction
  docs/1-Using-Fleet/configuration-files/README.md
Labels: :improve documentation

#1261 Add ability in Fleet UI for admin to create new users without email invitations
  changes/1261-admin-create-user-no-invite
  cypress/integration/all/app/activateuser.spec.ts
  frontend/components/TableContainer/DataTable/DropdownCell/_styles.scss
  frontend/components/forms/fields/Radio/Radio.tsx
  frontend/fleet/endpoints.ts
  frontend/fleet/entities/users.js
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.tests.jsx
  frontend/pages/admin/UserManagementPage/UsersTableConfig.tsx
  frontend/pages/admin/UserManagementPage/components/UserForm/UserForm.tsx
  frontend/pages/admin/UserManagementPage/components/UserForm/_styles.scss
  frontend/pages/admin/UserManagementPage/helpers/userManagementHelpers.tests.ts
  frontend/redux/nodes/entities/users/actions.js
  frontend/redux/nodes/entities/users/reducer.js
Labels: :frontend dev (Fleet UI)

#1340 Homepage Dashboard - New feature!
  assets/images/icon-arrow-right-vibrant-blue-10x18@2x.png
  assets/images/icon-linux-48x48@2x.png
  assets/images/icon-mac-48x48@2x.png
  assets/images/icon-windows-48x48@2x.png
  changes/issue-1319-home-page-host-summary
  frontend/components/side_panels/SiteNavHeader/SiteNavHeader.jsx
  frontend/components/side_panels/SiteNavHeader/_styles.scss
  frontend/components/side_panels/SiteNavHeader/index.js
  frontend/components/side_panels/SiteNavSidePanel/SiteNavSidePanel.jsx
  frontend/components/side_panels/SiteNavSidePanel/_styles.scss
  frontend/components/side_panels/SiteNavSidePanel/navItems.js
  frontend/layouts/CoreLayout/CoreLayout.jsx
  frontend/pages/Homepage/Dashboard/Dashboard.tsx
  frontend/pages/Homepage/Dashboard/HostsSummary/HostsSummary.tsx
  frontend/pages/Homepage/Dashboard/HostsSummary/_styles.scss
  frontend/pages/Homepage/Dashboard/HostsSummary/index.tsx
  frontend/pages/Homepage/Dashboard/_styles.scss
  frontend/pages/Homepage/Dashboard/index.tsx
  frontend/pages/Homepage/Homepage.jsx
  frontend/pages/Homepage/index.jsx
  frontend/router/index.jsx
  frontend/router/paths.ts
Labels: :frontend dev (Fleet UI)

#1355 Configure CodeQL Action
  .github/workflows/codeql-analysis.yml
Labels: #contributor experience

#1356 Increase timeout on Cypress enroll secret download
  cypress/integration/all/app/hosts.spec.ts
Labels: #contributor experience

#1366 User Modal: Fix default behaviors based on organization settings
  changes/1348-edit-user-modal
  frontend/interfaces/config.ts
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/admin/UserManagementPage/UsersTableConfig.tsx
  frontend/pages/admin/UserManagementPage/components/EditUserModal/EditUserModal.tsx
  frontend/pages/admin/UserManagementPage/components/UserForm/UserForm.tsx
Labels: :frontend dev (Fleet UI)

#1365 Dropdown Component: Clean Styling across Browsers
  changes/issue-1350-improve-firefox-dropdown-styling
  frontend/components/forms/fields/Dropdown/_styles.scss
  frontend/components/packs/PacksList/_styles.scss
  frontend/components/queries/QueriesList/_styles.scss
Labels: #spiffier

#1354 Create User Modal: No teams exists state
  changes/issue-1185-create-user-empty-teams
  frontend/pages/admin/UserManagementPage/components/UserForm/UserForm.tsx
  frontend/pages/admin/UserManagementPage/components/UserForm/_styles.scss
Labels: #spiffier

#1357 Configure CodeQL to target appropriate files
  .github/workflows/codeql-analysis.yml
  .github/workflows/config/codeql.yml
Labels: #contributor experience

#1369 Fix data race in inmem query results test
  server/pubsub/inmem_query_results.go
Labels: :golang dev, bug

#1389 Fix fleetctl NPM install with NPM 6
  tools/fleetctl-npm/package.json
  tools/fleetctl-npm/run.js
Labels: #fleetctl, bug

#1381 Watch video button and seamless cloud fix
  website/assets/images/clouds-1600x320@2x.png
  website/assets/images/clouds@2x.png
  website/assets/images/play-32x32@2x.png
  website/assets/styles/pages/homepage.less
  website/views/pages/homepage.ejs
Labels: #website

#1391 Launch transparency page for fleetdm.com
  website/api/controllers/view-transparency.js
  website/assets/images/emails-and-chat-101x81@2x.png
  website/assets/images/keystrokes-93x80@2x.png
  website/assets/images/mouse-movement-98x80@2x.png
  website/assets/images/privacy-80x92@2x.png
  website/assets/images/screen-82x81@2x.png
  website/assets/images/webcam-81x80@2x.png
  website/assets/js/pages/transparency.page.js
  website/assets/styles/importer.less
  website/assets/styles/pages/transparency.less
  website/config/policies.js
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/transparency.ejs
Labels: #website

#1390 Host Details Page: Software Inventory Searchable
  changes/issue-1363-software-inventory-searchable
  frontend/components/TableContainer/DataTable/DataTable.tsx
  frontend/components/TableContainer/DataTable/IconTooltipCell/IconTooltipCell.tsx
  frontend/components/TableContainer/DataTable/IconTooltipCell/index.ts
  frontend/components/TableContainer/TableContainer.tsx
  frontend/components/TableContainer/_styles.scss
  frontend/components/forms/fields/InputField/_styles.scss
  frontend/interfaces/software.ts
  frontend/interfaces/vulnerability.ts
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
  frontend/pages/admin/TeamManagementPage/TeamManagementPage.tsx
  frontend/pages/admin/UserManagementPage/UserManagementPage.jsx
  frontend/pages/hosts/HostDetailsPage/EmptySoftware/EmptySoftware.tsx
  frontend/pages/hosts/HostDetailsPage/EmptySoftware/_styles.scss
  frontend/pages/hosts/HostDetailsPage/EmptySoftware/index.ts
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareListRow/SoftwareListRow.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareListRow/_styles.scss
  frontend/pages/hosts/HostDetailsPage/SoftwareListRow/index.js
  frontend/pages/hosts/HostDetailsPage/SoftwareTable/SoftwareTableConfig.tsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: #spiffier, :frontend dev (Fleet UI)

#1392 Users management/Team management pages: Actions dropdown styling
  changes/issue-1255-action-dropdown-styling
  frontend/components/TableContainer/DataTable/DropdownCell/_styles.scss
  frontend/components/TableContainer/DataTable/_styles.scss
  frontend/components/forms/fields/Dropdown/_styles.scss
  frontend/pages/admin/TeamManagementPage/_styles.scss
  frontend/pages/admin/UserManagementPage/_styles.scss
Labels: #spiffier, :frontend dev (Fleet UI)

#1396 Update screenshots and verbiage in Configuring Single Sign On documentation
  docs/2-Deploying/2-Configuration.md
  docs/images/okta-idp-setup.png
  docs/images/sso-setup.png
Labels: :improve documentation

#1371 Fleetdm.com: Update query-detail page layout
  website/views/pages/query-detail.ejs
Labels: #website

#1398 Fleetdm.com: Add back button and update page styles for query library detail pages
  website/assets/styles/pages/query-detail.less
  website/views/pages/query-detail.ejs
Labels: #website

#1386 Query library improvements -- Round 3
  website/assets/styles/bootstrap-overrides.less
  website/assets/styles/pages/query-library.less
  website/views/pages/query-library.ejs
Labels: #website

#1410 Update development docker-compose.yml to use osquery 4.9.0
  tools/osquery/docker-compose.linux-overrides.yml
  tools/osquery/docker-compose.yml
Labels: #contributor experience

#1401 Add routes for Schedule feature to REST API documentation
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1414 Remove console warning
  website/views/layouts/layout.ejs
Labels: #website

#1427 Remove duplicate sections from REST API documentation
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1428 Add YARA configuration to documentation
  docs/1-Using-Fleet/configuration-files/README.md
  docs/1-Using-Fleet/configuration-files/single-file-configuration.yml
Labels: :improve documentation

#1444 Update support process documentation with instructions for customer feature requests
  handbook/support-process.md
Labels: :improve documentation

#1453 Add the query that populates the `users` property in Host vitals to the standard query library
  docs/1-Using-Fleet/standard-query-library/standard-query-library.yml
Labels: #query library

#1470 Add secondary select action buttons to DataTable
  frontend/components/TableContainer/DataTable/ActionButton/ActionButton.tsx
  frontend/components/TableContainer/DataTable/ActionButton/index.ts
  frontend/components/TableContainer/DataTable/DataTable.tsx
  frontend/components/TableContainer/DataTable/TextCell/TextCell.tsx
  frontend/components/TableContainer/TableContainer.tsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
Labels: :frontend dev (core platform)

#1333 Schedules Page - New Feature!
  assets/images/icon-error-16x16@2x.png
  assets/images/schedule.svg
  changes/issue-1333-global-schedule-frontend
  cypress/integration/all/app/queryflow.spec.ts
  cypress/integration/basic/admin.spec.ts
  cypress/integration/basic/maintainer.spec.ts
  cypress/integration/basic/observer.spec.ts
  cypress/integration/basic/team_maintainer_observer.spec.ts
  cypress/integration/core/admin.spec.ts
  cypress/integration/core/maintainer.spec.ts
  cypress/integration/core/observer.spec.ts
  frontend/components/TableContainer/DataTable/_styles.scss
  frontend/components/forms/ConfigurePackQueryForm/ConfigurePackQueryForm.jsx
  frontend/components/forms/ConfigurePackQueryForm/ConfigurePackQueryForm.tests.jsx
  frontend/components/forms/ConfigurePackQueryForm/validate.js
  frontend/components/schedule/SchedulePageWrapper/SchedulePageWrapper.jsx
  frontend/components/schedule/SchedulePageWrapper/index.js
  frontend/components/side_panels/ScheduleQuerySidePanel/ScheduleQuerySidePanel.jsx
  frontend/components/side_panels/SiteNavSidePanel/navItems.js
  frontend/fleet/endpoints.ts
  frontend/fleet/entities/global_scheduled_queries.js
  frontend/fleet/entities/global_scheduled_queries.tests.js
  frontend/fleet/helpers.tests.js
  frontend/fleet/helpers.ts
  frontend/fleet/index.js
  frontend/interfaces/global_scheduled_query.ts
  frontend/pages/admin/TeamManagementPage/TeamDetailsWrapper/MembersPagePage/MembersPage.tsx
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/SelectQueryModal/_styles.scss
  frontend/pages/hosts/HostDetailsPage/TransferHostModal/TransferHostModal.tsx
  frontend/pages/packs/EditPackPage/EditPackPage.jsx
  frontend/pages/schedule/ManageSchedulePage/ManageSchedulePage.tsx
  frontend/pages/schedule/ManageSchedulePage/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/RemoveScheduledQueryModal/RemoveScheduledQueryModal.tsx
  frontend/pages/schedule/ManageSchedulePage/components/RemoveScheduledQueryModal/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/RemoveScheduledQueryModal/index.ts
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleEditorModal/ScheduleEditorModal.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleEditorModal/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleEditorModal/index.ts
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleError/ScheduleError.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleError/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleError/index.ts
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleListWrapper.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleTableConfig.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/index.ts
  frontend/pages/schedule/ManageSchedulePage/index.ts
  frontend/redux/nodes/entities/base/schemas.js
  frontend/redux/nodes/entities/global_scheduled_queries/actions.js
  frontend/redux/nodes/entities/global_scheduled_queries/config.js
  frontend/redux/nodes/entities/global_scheduled_queries/reducer.js
  frontend/redux/nodes/entities/reducer.js
  frontend/router/index.jsx
  frontend/router/paths.ts
  frontend/styles/global/_global.scss
  frontend/test/mocks/global_scheduled_query_mocks.js
  frontend/test/mocks/index.js
  frontend/test/stubs.ts
  frontend/utilities/constants.ts
Labels: :frontend dev (core platform)

#1452 Launch new feature: Activity feed
  changes/1470-table-container
  changes/Issue-1320-activity-feed
  frontend/components/Avatar/Avatar.tsx
  frontend/components/Avatar/index.js
  frontend/components/Avatar/index.ts
  frontend/fleet/endpoints.ts
  frontend/fleet/entities/activities.ts
  frontend/fleet/index.js
  frontend/interfaces/activity.ts
  frontend/pages/Homepage/ActivityFeed/ActivityFeed.tsx
  frontend/pages/Homepage/ActivityFeed/_styles.scss
  frontend/pages/Homepage/ActivityFeed/index.tsx
  frontend/pages/Homepage/Dashboard/index.tsx
  frontend/pages/Homepage/Homepage.jsx
  frontend/pages/Homepage/Homepage.tsx
  frontend/pages/Homepage/HostsSummary/HostsSummary.tsx
  frontend/pages/Homepage/HostsSummary/_styles.scss
  frontend/pages/Homepage/HostsSummary/index.tsx
  frontend/pages/Homepage/_styles.scss
  frontend/router/index.jsx
Labels: :frontend dev (core platform)

#1487 Fix copy/paste mistake in docs ("Run live query" API)
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1492 Remove changes files, update release process docs, and update support process docs
  changes/1208-fetch-all-host-data
  changes/1239-improve-auth-errors
  changes/1261-admin-create-user-no-invite
  changes/1312-gcp-redis
  changes/1316-kinesis-firehose-errors
  changes/1348-edit-user-modal
  changes/1470-table-container
  changes/Issue-1320-activity-feed
  changes/issue-1009-inventory-software-reduce-inserts-deletes
  changes/issue-1098-flash-messages
  changes/issue-1185-create-user-empty-teams
  changes/issue-1206-create-pack
  changes/issue-1231-global-schedule
  changes/issue-1255-action-dropdown-styling
  changes/issue-1278-select-leader
  changes/issue-1286-improve-errors
  changes/issue-1292-limit-user-roles
  changes/issue-1300-add-host-users
  changes/issue-1319-home-page-host-summary
  changes/issue-1321-send-statistics
  changes/issue-1324-activity-feed
  changes/issue-1329-remove-duplicate-enroll-secrets
  changes/issue-1333-global-schedule-frontend
  changes/issue-1350-improve-firefox-dropdown-styling
  changes/issue-1359-fleetctl-host-transfer
  changes/issue-1360-fleetctl-user-delete
  changes/issue-1363-software-inventory-searchable
  changes/issue-1373-add-status-to-fleetctl-get-command
  changes/issue-1385-create-user-tooltips
  changes/issue-1447-tables-ascending-order
  changes/issue-296-disable-sso-for-users
  changes/issue-872-clear-host-settings-from-config
  changes/issue-966-remove-sources
  docs/3-Contributing/5-Releasing-Fleet.md
  handbook/support-process.md
Labels: :improve documentation

#1523 Edit padding on the "Home" page
  frontend/pages/Homepage/_styles.scss
Labels: #spiffier, :frontend dev (core platform)
