Repository fleetdm/fleet, pull requests merged in 2021-01, with the labels that each got.

#160 Updgrade webpack-notifier and node-notifier
  package.json
  yarn.lock
Labels: development infrastructure

#163 Add additional documentation on how the osquery configuration overrides option works.
  docs/1-Using-Fleet/2-fleetctl-CLI.md
Labels: documentation

#167 Complete setup with fleetctl preview
  cmd/fleetctl/config.go
  cmd/fleetctl/preview.go
Labels: enhancement

#180 Update osquery schema to 4.6.0
  frontend/osquery_tables.json
Labels: documentation

#182 Fix empty enroll secret before setup.
  server/datastore/datastore_app_test.go
  server/datastore/mysql/migrations/tables/20200512120000_CreateTableEnrollSecrets.go
Labels: bug

#207 Make name and secret required for enroll secrets
  server/service/service_appconfig.go
  server/service/service_appconfig_test.go
Labels: bug

#205 Expose live query error messages via API
  server/kolide/osquery.go
  server/launcher/launcher.go
  server/launcher/launcher_test.go
  server/mock/service_osquery.go
  server/service/endpoint_osquery.go
  server/service/logging_osquery.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/service/transport_osquery.go
  tools/osquery/docker-compose.yml
Labels: enhancement

#210 Upgrade osquery version in docker-compose to 4.5.1
  tools/osquery/docker-compose.yml
Labels: development infrastructure

#219 Add comments in generated flagfile
  frontend/components/hosts/AddHostModal/AddHostModal.jsx
Labels: spiffier

#223 Add host details in API responses
  server/kolide/hosts.go
  server/kolide/labels.go
  server/kolide/packs.go
  server/service/client_hosts.go
  server/service/endpoint_hosts.go
  server/service/logging_hosts.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
Labels: enhancement

#209 Add support for denylist parameter in scheduled queries
  server/datastore/datastore_packs_test.go
  server/datastore/datastore_scheduled_queries_test.go
  server/datastore/mysql/migrations/tables/20210119174155_AddDenylistToScheduledQueries.go
  server/datastore/mysql/packs.go
  server/datastore/mysql/scheduled_queries.go
  server/kolide/packs.go
  server/kolide/scheduled_queries.go
  server/service/endpoint_packs.go
Labels: bug, enhancement

#224 Reveal live query error information in Fleet UI
  frontend/components/hosts/HostsTable/_styles.scss
  frontend/components/loaders/ProgressBar/_styles.scss
  frontend/components/queries/QueryProgressDetails/QueryProgressDetails.jsx
  frontend/components/queries/QueryProgressDetails/_styles.scss
  frontend/components/queries/QueryResultsTable/QueryResultsTable.jsx
  frontend/components/queries/QueryResultsTable/QueryResultsTable.tests.jsx
  frontend/components/queries/QueryResultsTable/_styles.scss
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
  frontend/redux/nodes/entities/campaigns/helpers.js
  frontend/styles/var/colors.scss
  frontend/test/stubs.js
Labels: enhancement

#213 Add remaining hosts and osquery options endpoints to REST API docs.
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#218 Add queries endpoints to REST API docs.
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#234 Improvements to fleetctl preview experience
  cmd/fleetctl/preview.go
  go.mod
  go.sum
  server/service/client_errors.go
Labels: spiffier

#243 Update missing error message for Launcher
  frontend/redux/nodes/entities/campaigns/helpers.js
Labels: spiffier

#245 Expose live query error messages in fleetctl
  cmd/fleetctl/query_output.go
Labels: enhancement

#247 Start hosts in fleetctl preview
  cmd/fleetctl/preview.go
Labels: enhancement

#248 Update fleetctl preview instructions in README
  README.md
Labels: documentation
