Repository fleetdm/fleet, pull requests merged in 2021-04, with the labels that each got.

#571 On fleetdm.com, add stubbed "Pricing" page
  website/api/controllers/view-pricing.js
  website/assets/images/icon-hamburger-blue-16x14@2x.png
  website/assets/styles/importer.less
  website/assets/styles/layout.less
  website/assets/styles/pages/pricing.less
  website/config/policies.js
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/pricing.ejs
Labels: website

#572 Fix JS test warnings and errors on Node 15
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesList.tests.jsx
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.tests.jsx
  frontend/components/queries/ScheduledQueriesListWrapper/ScheduledQueriesListWrapper.tests.jsx
  frontend/interfaces/scheduled_query.ts
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
  frontend/test/envSetup.js
  package.json
  website/package.json
  yarn.lock
Labels: development infrastructure, frontend, refactoring

#579 Add GitHub Action to test website on PR
  .github/workflows/test-website.yml
Labels: development infrastructure, website

#581 Fix path for website test
  .github/workflows/test-website.yml
Labels: development infrastructure, website

#585 Speed up MySQL tests
  Makefile
  docker-compose.yml
  server/datastore/datastore_test.go
  server/datastore/mysql_test.go
  server/live_query/redis_live_query_test.go
  server/pubsub/query_results_test.go
  server/sso/session_store_test.go
Labels: development infrastructure, refactoring

#589 Fix E2E SSO testing
  cypress/support/commands.ts
  cypress/support/index.d.ts
Labels: development infrastructure

#586 Refactor MySQL tests into package mysql
  go.sum
  server/datastore/datastore.go
  server/datastore/datastore_app.go
  server/datastore/datastore_campaigns.go
  server/datastore/datastore_carves.go
  server/datastore/datastore_email_changes.go
  server/datastore/datastore_hosts.go
  server/datastore/datastore_invites.go
  server/datastore/datastore_labels.go
  server/datastore/datastore_migrations.go
  server/datastore/datastore_osquery_options.go
  server/datastore/datastore_packs.go
  server/datastore/datastore_password_reset.go
  server/datastore/datastore_queries.go
  server/datastore/datastore_scheduled_queries.go
  server/datastore/datastore_targets.go
  server/datastore/datastore_unicode.go
  server/datastore/datastore_users.go
  server/datastore/mysql/datastore_test.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/datastore/mysql_test.go
Labels: development infrastructure, refactoring

#576 Add role storage to invites APIs
  frontend/kolide/entities/invites.tests.js
  server/datastore/datastore_invites_test.go
  server/datastore/datastore_test.go
  server/datastore/inmem/invites.go
  server/datastore/mysql/invites.go
  server/datastore/mysql/migrations/tables/20210401111056_CreateTeamsTables.go
  server/datastore/mysql/migrations/tables/20210401164226_AddRolesToInvites.go
  server/kolide/invites.go
  server/kolide/users.go
  server/mock/datastore_invites.go
  server/service/service_users.go
Labels: teams/RBAC

#591 Remove invited_by from invite parameters
  docs/1-Using-Fleet/3-REST-API.md
  frontend/pages/admin/UserManagementPage/components/CreateUserForm/CreateUserForm.tsx
  server/datastore/datastore_queries_test.go
  server/datastore/mysql/errors.go
  server/datastore/mysql/invites.go
  server/kolide/invites.go
  server/mock/datastore_invites_helpers.go
  server/service/service_invites.go
  server/service/service_invites_test.go
  server/service/transport_invites_test.go
  server/service/validation_invites.go
Labels: refactoring

#590 Add get-started page to fleetdm.com
  website/assets/images/install-fleet-800x188@2x.png
  website/assets/images/intro-pic-800x364@2x.png
  website/assets/images/run-query-800x537@2x.png
  website/assets/styles/pages/get-started.less
  website/assets/styles/pages/pricing.less
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/get-started.ejs
  website/views/pages/pricing.ejs
Labels: website

#600 Add filtering for invites
  docs/1-Using-Fleet/3-REST-API.md
  server/datastore/mysql/invites.go
Labels: teams/RBAC

#604 Fix frontend bug on "Edit pack" page
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.jsx
  frontend/components/queries/ScheduledQueriesList/ScheduledQueriesListItem/ScheduledQueriesListItem.tests.jsx
  frontend/components/queries/ScheduledQueriesList/_styles.scss
Labels: bug, frontend

#605 Fix carve documentation flag order
  docs/1-Using-Fleet/2-fleetctl-CLI.md
Labels: documentation

#609 Migrate old admin field to new global role
  server/contexts/viewer/viewer.go
  server/contexts/viewer/viewer_test.go
  server/datastore/datastore_invites_test.go
  server/datastore/datastore_users_test.go
  server/datastore/inmem/inmem.go
  server/datastore/mysql/invites.go
  server/datastore/mysql/migrations/tables/20210406113434_MigrateAdmin.go
  server/datastore/mysql/users.go
  server/kolide/invites.go
  server/kolide/users.go
  server/service/endpoint_middleware_test.go
  server/service/endpoint_setup.go
  server/service/endpoint_test.go
  server/service/endpoint_users_test.go
  server/service/handler_test.go
  server/service/http_auth_test.go
  server/service/service_invites.go
  server/service/service_invites_test.go
  server/service/service_users.go
  server/service/service_users_test.go
  server/service/util_test.go
  server/service/validation_invites.go
  server/test/new_objects.go
Labels: teams/RBAC

#613 Provide documentation for reporting issues with the Fleet UI
  .github/ISSUE_TEMPLATE/bug-report.md
  CONTRIBUTING.md
  docs/3-Contribution/4-Committing-Changes.md
  docs/3-Contribution/README.md
  docs/images/my-account-page.png
Labels: documentation

#619 Clean up Go dependencies
  go.mod
  go.sum
  server/service/debug_handler_test.go
Labels: refactoring

#622 Delete instead of disabling users
  docs/1-Using-Fleet/3-REST-API.md
  server/contexts/viewer/viewer.go
  server/contexts/viewer/viewer_test.go
  server/datastore/inmem/inmem.go
  server/datastore/mysql/migrations/tables/20210408153510_DeleteUsers.go
  server/datastore/mysql/queries.go
  server/datastore/mysql/users.go
  server/kolide/users.go
  server/mock/datastore_users.go
  server/service/debug_handler_test.go
  server/service/endpoint_users.go
  server/service/handler.go
  server/service/logging_users.go
  server/service/metrics_users.go
  server/service/service_sessions.go
  server/service/service_users.go
  server/service/service_users_test.go
  server/service/transport_users.go
  server/service/util_test.go
Labels: teams/RBAC

#623 Include empty teams array in invites
  server/kolide/invites.go
Labels: teams/RBAC

#630 Add Detect high severity vulnerable versions of OpenSSL to query handbook
  handbook/queries/detect-hosts-with-high-severity-vulnerable-versions-of-openssl.md
Labels: query library

#632 Fix saving of teams in invitations
  server/datastore/mysql/invites.go
  server/kolide/invites.go
  server/service/service_invites.go
Labels: teams/RBAC

#631 Support .exe files in fleetctl updates command
  ee/fleetctl/updates.go
Labels: orbit

#634 Prepare queries for Software inventory
  handbook/queries/get-installed-freebsd-software.md
  handbook/queries/get-installed-linux-software.md
  handbook/queries/get-installed-macos-software.md
  handbook/queries/get-installed-windows-software.md
Labels: query library

#633 Batch updates to host seen time
  cmd/fleet/serve.go
  docker-compose.yml
  server/datastore/datastore.go
  server/datastore/datastore_hosts.go
  server/datastore/mysql/hosts.go
  server/kolide/hosts.go
  server/mock/datastore_hosts.go
  server/service/service.go
  server/service/service_hosts.go
  server/service/service_invites_test.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
Labels: enhancement, refactoring

#621 Update testimonials on homepage
  website/views/pages/homepage.ejs
Labels: website

#637 Add documentation for connecting to development MySQL shell
  docs/3-Contribution/2-Testing.md
Labels: development infrastructure, documentation

#641 Handle live query case when selected target contains 0 hosts
  frontend/pages/queries/QueryPage/QueryPage.jsx
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
Labels: frontend

#642 Handle hosts that have not had details updated in "Hosts" table
  frontend/kolide/helpers.ts
Labels: frontend

#644 Edit label and Add label frontend fixes
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.tests.jsx
Labels: frontend

#657 Speed up CI build/test
  .github/workflows/test.yml
  Makefile
  package.json
  webpack.config.js
  yarn.lock
Labels: development infrastructure

#656 Update documentation about TLS configuration
  docs/2-Deployment/1-Installation.md
  docs/2-Deployment/2-Configuration.md
  docs/2-Deployment/FAQ.md
Labels: documentation

#666 Add delete teams endpoints
  server/datastore/datastore.go
  server/datastore/datastore_teams.go
  server/datastore/mysql/teams.go
  server/kolide/teams.go
  server/service/endpoint_teams.go
  server/service/handler.go
  server/service/service_teams.go
  server/service/transport_teams.go
Labels: teams/RBAC

#668 Add host and user counts to list teams response
  server/datastore/mysql/teams.go
  server/kolide/teams.go
Labels: teams/RBAC

#672 Add team user management
  server/datastore/datastore.go
  server/datastore/datastore_teams.go
  server/datastore/datastore_users.go
  server/datastore/inmem/users.go
  server/datastore/mysql/teams.go
  server/datastore/mysql/users.go
  server/kolide/teams.go
  server/kolide/users.go
  server/mock/datastore_users.go
  server/service/endpoint_teams.go
  server/service/endpoint_users.go
  server/service/handler.go
  server/service/logging_users.go
  server/service/metrics_users.go
  server/service/service_teams.go
  server/service/service_users.go
  server/service/transport.go
  server/service/transport_teams.go
  server/service/transport_users.go
Labels: teams/RBAC

#679 Update flags for development cAdvisor
  docker-compose.yml
Labels: development infrastructure

#678 Initial backend software inventory implementation
  docs/2-Deployment/2-Configuration.md
  go.mod
  go.sum
  handbook/queries/get-installed-macos-software.md
  handbook/queries/get-installed-windows-software.md
  server/datastore/datastore.go
  server/datastore/datastore_software.go
  server/datastore/mysql/migrations/tables/20210421112652_AddSoftwareInventory.go
  server/datastore/mysql/software.go
  server/kolide/datastore.go
  server/kolide/hosts.go
  server/kolide/software.go
  server/mock/datastore.go
  server/mock/datastore_software.go
  server/service/service_hosts.go
  server/service/service_hosts_test.go
  server/service/service_osquery.go
  server/service/service_osquery_test.go
  server/test/comparisons.go
Labels: enhancement

#688 Fixes issue #0
  website/config/routes.js
  website/views/layouts/layout.ejs
Labels: website

#689 Fix handling of MySQL TLS flags
  server/datastore/mysql/mysql.go
Labels: bug

#671 Add api/v1/status/ endpoints and api/v1/sso/callback endpoint to REST API docs
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#669 Draft API changes to api/v1/fleet/hosts/{id} endpoint for software inventory
  docs/1-Using-Fleet/3-REST-API.md
Labels: documentation

#700 Fix link to stubs
  frontend/test/README.md
Labels: documentation
