Repository fleetdm/fleet, pull requests merged in 2021-11, with the labels that each got.

#2754 Update policy passing icon filename and style on "Home" page
  assets/images/icon-check-circle-green-16x16@2x.png
Labels: #spiffier

#2743 Add a new "API for contributors" documentation page
  docs/01-Using-Fleet/03-REST-API.md
  docs/03-Contributing/07-API-for-contributors.md
Labels: :improve documentation

#2775 Fix autoformatting for fleetdm.com website source
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: #contributor experience, :frontend dev (website)

#2784 update product.md to include Quality objectives
  handbook/product.md
Labels: :improve documentation

#2805 Update Go versions to 1.17.2
  .github/workflows/goreleaser-fleet.yaml
  .github/workflows/goreleaser-orbit.yaml
  .github/workflows/goreleaser-snapshot-fleet.yaml
  .github/workflows/test-go.yaml
Labels: :golang dev

#2779 Add top level links to "Contributing" section and move up Load testing "Results"
  docs/02-Deploying/05-Load-testing.md
  docs/03-Contributing/README.md
Labels: :improve documentation

#2833 Fix typo in build docs
  docs/03-Contributing/01-Building-Fleet.md
Labels: :improve documentation

#2840 Update documentation for `/policies` API routes
  docs/01-Using-Fleet/03-REST-API.md
Labels: :improve documentation

#2652 Update documentation for patch releases
  docs/03-Contributing/05-Releasing-Fleet.md
Labels: :improve documentation

#2863 Upgrade node-sass for Node 16 compatibility
  package.json
  yarn.lock
Labels: #contributor experience, :frontend dev (core platform)

#2870 In API docs, update description for `GET /software` parameters
  docs/01-Using-Fleet/03-REST-API.md
Labels: :improve documentation

#2892 Update documentation for `/policies` API routes
  docs/01-Using-Fleet/03-REST-API.md
Labels: :improve documentation

#2906 Fix broken link in "Osquery logs" documentation
  docs/01-Using-Fleet/05-Osquery-logs.md
  handbook/product.md
Labels: :improve documentation, :improve handbook

#2913 Update changelog for 4.5.1 release
  CHANGELOG.md
  changes/fix-2785
  changes/issue-2628-2697-query-compatibility
  changes/issue-2778-packs-get-always-returns-disabled
  changes/issue-2785-manage-queries-fix
  changes/issue-2822-dashboard-host-change-on-team
  changes/issue-2868-ignore-admin-reset-password-sso
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/fleetctl-npm/package.json
Labels: :improve documentation

#2831 Implement `fleetctl updates rotate`
  Makefile
  changes/updates-rotate
  docs/02-Deploying/04-fleetctl-agent-updates.md
  ee/fleetctl/updates.go
  ee/fleetctl/updates_test.go
  ee/fleetctl/updates_windows.go
  go.mod
  go.sum
  orbit/pkg/packaging/macos.go
  orbit/pkg/packaging/packaging.go
  orbit/pkg/packaging/windows.go
  orbit/pkg/update/badgerstore/badgerstore.go
  orbit/pkg/update/badgerstore/badgerstore_test.go
  orbit/pkg/update/filestore/filestore.go
  orbit/pkg/update/filestore/filestore_test.go
  orbit/pkg/update/update.go
  pkg/file/file.go
  pkg/file/file_test.go
  server/datastore/mysql/labels.go
Labels: #agent autoupdater, :golang dev, #fleetctl

#2966 on multiple enrollments
  docs/03-Contributing/FAQ.md
Labels: :improve documentation

#2970 Update oncall process
  handbook/product.md
Labels: :improve documentation

#2989 Document enroll secret rotation
  docs/02-Deploying/FAQ.md
Labels: :improve documentation

#2947 Add additional tables and Windows support in Orbit extension
  orbit/changes/extension-tables
  orbit/cmd/orbit/orbit.go
  orbit/cmd/orbit/shell.go
  orbit/pkg/osquery/osquery.go
  orbit/pkg/table/extension.go
  orbit/pkg/table/extension_darwin.go
Labels: #agent autoupdater, :golang dev

#3006 Add osquery flagfile support in Orbit
  changes/flagfile-support
  cmd/fleetctl/package.go
  orbit/changes/flagfile-support
  orbit/cmd/orbit/orbit.go
  orbit/pkg/packaging/linux_shared.go
  orbit/pkg/packaging/macos.go
  orbit/pkg/packaging/packaging.go
  orbit/pkg/packaging/windows.go
  orbit/pkg/table/extension.go
Labels: #agent autoupdater, :golang dev

#3009 Filter GitHub actions triggers on file types
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-fleet-website.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test-go.yaml
Labels: #contributor experience

#3008 Use UUID as default host identifier for Orbit
  orbit/changes/uuid-identifier
  orbit/pkg/osquery/flags.go
Labels: #agent autoupdater, :golang dev

#3034 Change Orbit osquery to Fleet osquery in generated packages
  changes/fleetctl-package-names
  cmd/fleetctl/package_test.go
  orbit/pkg/packaging/linux_shared.go
  orbit/pkg/packaging/macos.go
  orbit/pkg/packaging/macos_templates.go
  orbit/pkg/packaging/windows.go
  orbit/pkg/packaging/windows_templates.go
Labels: #agent autoupdater, :golang dev

#3035 Fix missing import on Windows
  ee/fleetctl/updates_windows.go
Labels: :golang dev

#2956 Update "Adding hosts" documentation to emphasize osquery installers
  docs/01-Using-Fleet/04-Adding-hosts.md
  docs/01-Using-Fleet/10-Teams.md
  docs/02-Deploying/01-Installation.md
  docs/02-Deploying/02-Configuration.md
  tools/mac/Makefile
  tools/mac/config.mk
  tools/mac/root/Library/LaunchDaemons/co.kolide.osquery.enroll.plist
  tools/mac/scripts/postinstall
Labels: :improve documentation

#3066 Disable storage of errors
  server/errorstore/errors.go
  server/errorstore/errors_test.go
Labels: bug, :golang dev

#2967 Add `fleetctl debug migrations` command to get missing migrations
  changes/issue-2463-fleetctl-debug-migrations
  cmd/fleet/prepare.go
  cmd/fleet/serve.go
  cmd/fleetctl/debug.go
  server/datastore/mysql/migrations_test.go
  server/datastore/mysql/mysql.go
  server/datastore/mysql/mysql_test.go
  server/fleet/datastore.go
  server/mock/datastore.go
  server/mock/datastore_mock.go
  server/service/client_debug.go
  server/service/debug_handler.go
  server/service/debug_handler_test.go
Labels: :golang dev
