Repository fleetdm/fleet, pull requests merged in 2021-08, with the labels that each got.

#1529 Add /activities API route to API documentation
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1530 Add "Asking questions about your devices" tutorial to "Using Fleet" documentation
  README.md
  docs/1-Using-Fleet/1-Fleet-UI.md
  docs/1-Using-Fleet/tutorials/Ask-questions-about-your-devices.md
Labels: :improve documentation

#1525 Schedules page: Action cell (Update and delete a global scheduled query)
  changes/issue-1525-schedule-action-dropdown
  cypress/integration/all/app/queryflow.spec.ts
  frontend/components/TableContainer/DataTable/_styles.scss
  frontend/components/modals/Modal/_styles.scss
  frontend/interfaces/global_scheduled_query.ts
  frontend/pages/admin/TeamManagementPage/_styles.scss
  frontend/pages/admin/UserManagementPage/_styles.scss
  frontend/pages/schedule/ManageSchedulePage/ManageSchedulePage.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleEditorModal/ScheduleEditorModal.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleListWrapper.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleTableConfig.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/_styles.scss
Labels: #spiffier, :frontend dev (core platform)

#1539 Update usage of os.IsNotExist
  cmd/fleetctl/config.go
  server/logging/filesystem.go
  server/vulnerabilities/cpe_test.go
  server/vulnerabilities/db.go
Labels: :golang dev, :refactor

#1526 Refactor manage queries page
  assets/images/icon-delete-vibrant-blue-12x14@2x.png
  changes/1526-refactor-manage-queries-page
  cypress/integration/all/app/queryflow.spec.ts
  cypress/integration/basic/maintainer.spec.ts
  cypress/integration/basic/observer.spec.ts
  cypress/integration/core/admin.spec.ts
  cypress/integration/core/maintainer.spec.ts
  cypress/integration/core/observer.spec.ts
  frontend/components/TableContainer/DataTable/ActionButton/ActionButton.tsx
  frontend/components/TableContainer/DataTable/ActionButton/_styles.scss
  frontend/components/TableContainer/DataTable/DataTable.tsx
  frontend/components/TableContainer/DataTable/_styles.scss
  frontend/interfaces/query.ts
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.jsx
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.tests.jsx
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.tsx
  frontend/pages/queries/ManageQueriesPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/components/QueriesListError/QueriesListError.tsx
  frontend/pages/queries/ManageQueriesPage/components/QueriesListError/_styles.scss
  frontend/pages/queries/ManageQueriesPage/components/QueriesListError/index.ts
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/QueriesListWrapper.tsx
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/QueriesTableConfig.tsx
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/_styles.scss
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/index.ts
  frontend/pages/queries/ManageQueriesPage/components/RemoveQueryModal/RemoveQueryModal.tsx
  frontend/pages/queries/ManageQueriesPage/components/RemoveQueryModal/_styles.scss
  frontend/pages/queries/ManageQueriesPage/components/RemoveQueryModal/index.ts
  frontend/pages/queries/ManageQueriesPage/index.tsx
Labels: :frontend dev (core platform)

#1548 Add valid time units to Configuration documentation
  docs/2-Deploying/2-Configuration.md
Labels: :improve documentation

#1568 Update JWT library to github.com/golang-jwt/jwt
  ee/server/licensing/licensing.go
  go.mod
  go.sum
Labels: :refactor, :golang dev

#1586 Cleanup unused FetchPEM function
  orbit/pkg/certificate/certificate.go
  orbit/pkg/certificate/certificate_test.go
Labels: :golang dev

#1538 Improve handling of empty passphrase and initialized updates repo
  ee/fleetctl/updates.go
  ee/fleetctl/updates_test.go
Labels: #agent autoupdater

#1606 Add yarn install to Windows instructions
  docs/3-Contributing/1-Building-Fleet.md
Labels: :improve documentation

#1603 Fix live query for observers
  server/service/service_campaigns.go
  server/service/service_status.go
Labels: bug, :golang dev

#1592 Add new feature: filter hosts by team
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/services/entities/hosts.ts
Labels: :frontend dev (core platform)

#1614 ManageQueriesPage: Table loading state
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.tsx
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/QueriesListWrapper.tsx
Labels: :frontend dev (core platform)

#1605 Remove duplicate registration of results handler
  server/service/handler.go
Labels: :refactor, :golang dev

#1635 Disable edit label page select platform dropdown
  changes/1627-fix-edit-label-platform
  cypress/integration/all/app/labelflow.spec.ts
  frontend/components/forms/LabelForm/LabelForm.jsx
  frontend/components/forms/LabelForm/_styles.scss
Labels: :frontend dev (core platform)

#1633 Clarify label responses and API docs
  docs/1-Using-Fleet/3-REST-API.md
  server/fleet/labels.go
Labels: :improve documentation, :golang dev

#1650 Update goreleaser configs for 4.2.0
  .github/workflows/goreleaser-fleet.yaml
  .github/workflows/goreleaser-orbit.yaml
  .goreleaser.yml
Labels: #contributor experience

#1663 Fleetdm.com: Replace osquery logo
  website/assets/images/logo-osquery-137x40@2x.png
  website/assets/images/logo-osquery-89x24@2x.png
  website/views/pages/pricing.ejs
Labels: :frontend dev (website)

#1669 Add correct query for "Get installed Chrome Extensions"
  docs/1-Using-Fleet/standard-query-library/standard-query-library.yml
Labels: #query library

#1670 Update "Ask questions about your devices" walkthrough and update API docs
  docs/1-Using-Fleet/3-REST-API.md
  docs/1-Using-Fleet/tutorials/Ask-questions-about-your-devices.md
Labels: :improve documentation

#1678 Document minimal online keys for Orbit updates
  docs/2-Deploying/4-fleetctl-agent-updates.md
Labels: :improve documentation, #agent autoupdater

#1676 Reorder load of standard queries in fleetctl preview
  cmd/fleetctl/preview.go
Labels: #fleetctl preview

#1691 Prevent strange rendering of "Hosts" table at smaller screen widths
  frontend/styles/global/_global.scss
Labels: #spiffier

#1684 Add new loading spinner, edit `text-icon` buttons (spiffier) and rename `SiteNavSidePanel`
  assets/images/icon-edit-columns-16x12@2x.png
  assets/images/icon-edit-columns-16x16@2x.png
  frontend/components/TableContainer/TableContainer.tsx
  frontend/components/buttons/Button/_styles.scss
  frontend/components/loaders/Spinner/Spinner.tsx
  frontend/components/loaders/Spinner/_styles.scss
  frontend/components/side_panels/SiteNavSidePanel/index.js
  frontend/components/side_panels/SiteTopNav/SiteTopNav.jsx
  frontend/components/side_panels/SiteTopNav/_styles.scss
  frontend/components/side_panels/SiteTopNav/index.js
  frontend/components/side_panels/SiteTopNav/navItems.js
  frontend/layouts/CoreLayout/CoreLayout.jsx
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/packs/ManagePacksPage/components/PacksListWrapper/PacksListWrapper.tsx
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/QueriesListWrapper.tsx
  frontend/pages/schedule/ManageSchedulePage/components/ScheduleListWrapper/ScheduleListWrapper.tsx
Labels: #spiffier, :refactor

#1692 Clarify a few points in the Contributing docs
  docs/3-Contributing/1-Building-Fleet.md
  docs/3-Contributing/4-Committing-Changes.md
Labels: :improve documentation

#1680 FleetUI: Update column sort options
  changes/Issue1507-disable-sort-remove
  frontend/components/TableContainer/DataTable/DataTable.tsx
  frontend/components/TableContainer/TableContainer.tsx
  frontend/fleet/entities/hosts.tests.js
  frontend/fleet/entities/hosts.ts
  frontend/test/mocks/host_mocks.js
Labels: :frontend dev (core platform)

#1686 Add explicit sync to disk for critical file writes
  changes/issue-1679-sync-file-writes
  cmd/fleetctl/config.go
  orbit/pkg/packaging/linux_shared.go
  orbit/pkg/packaging/macos.go
  orbit/pkg/packaging/packaging.go
  orbit/pkg/update/filestore/filestore.go
Labels: #agent autoupdater, :golang dev

#1701 Add minimum width for Fleet UI and "Pack" tables on "Host details" page and "Queries" table
  cypress/integration/basic/teamflow.spec.ts
  frontend/components/side_panels/SecondarySidePanelContainer/_styles.scss
  frontend/layouts/CoreLayout/_styles.scss
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/PackTable/PackTableConfig.tsx
  frontend/pages/hosts/HostDetailsPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/components/QueriesListWrapper/_styles.scss
  frontend/styles/global/_global.scss
  frontend/styles/var/_global.scss
Labels: #spiffier

#1722 Move vulnerabilities configuration options into 2-Deploying/2-Configuration.md
  docs/1-Using-Fleet/13-Vulnerability-Processing.md
  docs/2-Deploying/2-Configuration.md
Labels: :improve documentation

#1725 Clarify Safari in supported browsers doc
  docs/1-Using-Fleet/12-Supported-browsers.md
Labels: :improve documentation

#1738 Fix anchor links for "Get enroll secrets" and "Modify enroll secrets" sections in API docs
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1744 Update host API doc
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1745 Update live query API documentation
  docs/1-Using-Fleet/3-REST-API.md
Labels: :improve documentation

#1721 New "Get started" page on fleetdm.com
  website/assets/images/logo-docker-51x36@2x.png
  website/assets/images/logo-node-59x36@2x.png
  website/assets/images/logo-slack-24x24@2x.png
  website/assets/images/logo-slack-28x28@2x.png
  website/assets/styles/bootstrap-overrides.less
  website/assets/styles/mixins-and-variables/typography.less
  website/assets/styles/pages/get-started.less
  website/config/routes.js
  website/views/layouts/layout.ejs
  website/views/pages/get-started.ejs
Labels: #website, :frontend dev (website), #growth

#1742 Activity feed initial empty state
  changes/minor-change-activity-feed
  frontend/pages/Homepage/ActivityFeed/ActivityFeed.tsx
Labels: #spiffier, :frontend dev (core platform)

#1740 Add host modal: Select team dropdown
  changes/1694-team-maintainer-add-host
  cypress/integration/all/app/hosts.spec.ts
  cypress/integration/basic/admin.spec.ts
  cypress/integration/basic/team_maintainer_observer.spec.ts
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.jsx
  frontend/pages/hosts/ManageHostsPage/components/AddHostModal/AddHostModal.jsx
Labels: :frontend dev (core platform)

#1765 Add location of licensing credentials
  ee/tools/license/README.md
Labels: :improve documentation

#1746 Refresh host details after team transfer
  changes/1719-host-details-transfer-team
  cypress/integration/all/app/hosts.spec.ts
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.jsx
  frontend/pages/hosts/HostDetailsPage/HostDetailsPage.tests.jsx
Labels: :frontend dev (core platform)

#1780 Add retries for flaky admin test
  cypress/integration/basic/admin.spec.ts
Labels: #contributor experience, :frontend dev (core platform)

#1790 Add "New feature work" issue template
  .github/ISSUE_TEMPLATE/new-feature-work.md
Labels: #contributor experience

#1849 Fleetdm.com: Fix browser compatibility issues
  website/assets/styles/pages/pricing.less
  website/assets/styles/pages/query-library.less
  website/views/layouts/layout.ejs
  website/views/pages/pricing.ejs
Labels: #website, :frontend dev (website)

#1854 Add canonical URL for link to prometheus example configuration
  docs/1-Using-Fleet/6-Monitoring-Fleet.md
Labels: :improve documentation

#1864 Add Schedule feature to permissions documentation
  docs/1-Using-Fleet/9-Permissions.md
Labels: :improve documentation

#1871 Adjust software vulnerabilities UI
  frontend/components/IconToolTip/IconToolTip.tsx
  frontend/pages/hosts/HostDetailsPage/SoftwareVulnerabilities/SoftwareVulnerabilities.jsx
  frontend/pages/hosts/HostDetailsPage/SoftwareVulnerabilities/_styles.scss
  frontend/pages/hosts/HostDetailsPage/_styles.scss
Labels: #spiffier, :frontend dev (core platform), #core
