Repository fleetdm/fleet, pull requests merged in 2022-04, with the labels that each got.

#4952 Add optimization to Windows software query
  changes/issue-4261-software-query
  server/service/osquery_utils/queries.go
Labels: :backend, performance

#4726 Replace uses of ansi quotes (") in SQL statements
  server/datastore/mysql/aggregated_stats_test.go
  server/datastore/mysql/hosts.go
  server/datastore/mysql/migrations/tables/20171116163618_CreateTableOsqueryOptions.go
  server/datastore/mysql/migrations/tables/20211116184030_PolicyWithProprietaryQuery.go
  server/datastore/mysql/queries.go
  server/datastore/mysql/scheduled_queries.go
Labels: :community

#4794 Run CodeQL on every commit to main
  .github/workflows/codeql-analysis.yml
Labels: #contributor experience

#5032 Make Orbit update interval configurable
  cmd/fleetctl/package.go
  orbit/changes/orbit-update-interval
  orbit/cmd/orbit/orbit.go
  orbit/pkg/packaging/linux_shared.go
  orbit/pkg/packaging/macos_templates.go
  orbit/pkg/packaging/packaging.go
  orbit/pkg/packaging/windows_templates.go
  tools/tuf/init_tuf.sh
Labels: #agent autoupdater

#5119 Skip Docker interfaces for host primary IP
  changes/issue-4754-docker-interface
  server/service/osquery_utils/queries.go
  server/service/osquery_utils/queries_test.go
Labels: bug, :backend

#5282 Prepare for Orbit 0.0.9
  orbit/CHANGELOG.md
  orbit/changes/orbit-update-interval
Labels: :improve documentation

#5312 Update get started (fleetctl preview) instructions on website
  website/views/pages/get-started.ejs
Labels: #website

#5421 Document supported MySQL versions
  .github/workflows/test-go.yaml
  docker-compose.yml
  docs/Deploying/FAQ.md
Labels: :improve documentation, #contributor experience
