Repository fleetdm/fleet, pull requests merged in 2022-02, with the labels that each got.

#3958 Allow reinstallation of MSI packages
  changes/reinstall-msi
  orbit/pkg/packaging/windows_templates.go
Labels: #agent autoupdater

#3972 Update triggers for link check Action
  .github/workflows/docs.yml
Labels: #contributor experience

#3996 Prepare for 4.9.1 release
  CHANGELOG.md
  changes/3660-hosts-filter-state
  changes/issue-3854-fix-schedules-api-calls
  changes/reinstall-msi
  changes/sso-check-audience
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/fleetctl-npm/package.json
Labels: :improve documentation

#4076 Add quoting around string in query library using colon
  docs/01-Using-Fleet/standard-query-library/standard-query-library.yml
Labels: :improve documentation

#4005 Prepare for 4.9.1 release (#3996)
  CHANGELOG.md
  changes/issue-3854-fix-schedules-api-calls
  changes/reinstall-msi
  changes/sso-check-audience
  charts/fleet/Chart.yaml
  charts/fleet/values.yaml
  tools/fleetctl-npm/package.json
Labels: :improve documentation

#4130 Add vulnerability automations to "Automations" docs
  docs/01-Using-Fleet/03-REST-API.md
  docs/01-Using-Fleet/14-Automations.md
  docs/01-Using-Fleet/configuration-files/README.md
Labels: :improve documentation

#4077 Allow short IdP name in server validation
  changes/allow-short-idp-name
  server/service/appconfig.go
  server/service/appconfig_test.go
Labels: :golang dev

#4185 Fix date of 4.10.0 release in changelog
  CHANGELOG.md
Labels: :improve documentation

#4197 [4196] Adding vulnerability management information
  handbook/README.md
  handbook/security.md
  website/.sailsrc
Labels: :security

#4322 Update OSSF Scorecard Analysis to 1.0.4
  .github/workflows/scorecards-analysis.yml
Labels: :security
