Repository fleetdm/fleet, pull requests merged in 2022-01, with the labels that each got.

#3545 Add integration test for fleetctl preview
  .github/workflows/fleetctl-preview.yml
Labels: :golang dev

#3550 Make Linux postinstall more permissive
  orbit/pkg/packaging/linux_shared.go
Labels: #agent autoupdater, :golang dev

#3562 Update development license
  cmd/fleet/serve.go
Labels: #contributor experience

#3566 Pin actions to commit
  .github/workflows/deploy-fleet-website.yml
  .github/workflows/docs.yml
Labels: #contributor experience

#3629 Add product process to handbook and update vuln processing docs
  docs/01-Using-Fleet/13-Vulnerability-Processing.md
  handbook/product.md
Labels: :improve documentation, :improve handbook

#3650 Update product handbook
  handbook/README.md
  handbook/product.md
Labels: :improve handbook

#3674 Only run E2E tests on relevant commits
  .github/workflows/test.yml
Labels: #contributor experience

#3633 Integration test packaging
  .github/workflows/deploy-staging.yml
  .github/workflows/integration.yml
Labels: #agent autoupdater, #fleetctl preview

#3632 Remove unused request-id in context
  server/service/http_auth.go
Labels: :golang dev, techdebt

#3682 Orbit 0.0.6 changelog
  changes/issue-3100-add-windows-orbit-osquery-logging
  changes/issue-3522-increase-extension-register-timeout
  orbit/CHANGELOG.md
Labels: :improve documentation, #agent autoupdater

#3687 Improve Orbit debug logging
  orbit/cmd/orbit/orbit.go
  orbit/pkg/osquery/osquery.go
  orbit/pkg/table/extension.go
  orbit/pkg/update/runner.go
Labels: #agent autoupdater

#3688 How to update the handbook
  handbook/handbook.md
Labels: #contributor experience

#3698 Update FAQ for duplicate host enrollment
  docs/02-Deploying/FAQ.md
Labels: :improve documentation

#3733 Include browser extensions in software inventory
  changes/issue-3557-browser-extensions
  server/service/osquery_utils/queries.go
Labels: bug

#3769 Simplify docker publish action
  .github/workflows/goreleaser-snapshot-fleet.yaml
Labels: #contributor experience

#3775 Shorten "simple" query API period to 25s
  changes/query-timeout
  docs/01-Using-Fleet/03-REST-API.md
  server/service/live_queries.go
Labels: :golang dev

#3805 Skip link check for goreportcard.com
  .github/workflows/markdown-link-check-config.json
Labels: #contributor experience

#3803 Alias fleetctl sandbox to fleetctl preview
  cmd/fleetctl/preview.go
Labels: #fleetctl preview

#3838 Remove dangling sentence in infrastructure docs
  docs/02-Deploying/01-Introduction.md
Labels: :improve documentation

#3884 Update handbook section on meetings
  handbook/people.md
Labels: :improve handbook
