Repository fleetdm/fleet, pull requests merged in 2022-03, with the labels that each got.

#4520 Update Orbit changelog for 0.0.7
  orbit/CHANGELOG.md
  orbit/changes/3679-orbit-wait-for-osquery-ext-manager-socket
  orbit/changes/issue-3456-fix-orbit-update-check-at-startup
  orbit/changes/issue-4146-orbit-osquery-logpath
Labels: :improve documentation

#4622 4620 pin action dependencies
  .github/workflows/build-binaries.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-fleet-website.yml
  .github/workflows/docs.yml
  .github/workflows/fleet-and-orbit.yml
  .github/workflows/generate-osqueryd-app-tar-gz.yml
  .github/workflows/goreleaser-fleet.yaml
  .github/workflows/goreleaser-orbit.yaml
  .github/workflows/goreleaser-snapshot-fleet.yaml
  .github/workflows/integration.yml
  .github/workflows/pr-helm.yaml
  .github/workflows/push-osquery-perf-to-ecr.yml
  .github/workflows/release-helm.yaml
  .github/workflows/semgrep-analysis.yml
  .github/workflows/test-go.yaml
  .github/workflows/test-packaging.yml
  .github/workflows/test-website.yml
  .github/workflows/test.yml
Labels: :security

#4661 Fix race condition in updates test
  orbit/pkg/update/update_test.go
  server/datastore/mysql/migrations/tables/20201011162341_CleanupSoftDeletedColumns.go
Labels: :golang dev

#4665 Add GitHub security guide
  handbook/README.md
  handbook/security.md
Labels: :improve handbook, :security

#4772 Allow Orbit shell to run while daemon is running
  orbit/changes/fix-shell
  orbit/cmd/orbit/shell.go
Labels: bug, #agent autoupdater
